Repository openrewrite/rewrite, pull requests merged in 2021-11, with the labels that each got.

#1172 BlankLines formatting on nested classes and enums
  rewrite-java/src/main/java/org/openrewrite/java/format/BlankLinesVisitor.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/format/BlankLinesTest.kt
Labels: bug

#1188 Name case convention utilities
  rewrite-core/src/main/java/org/openrewrite/internal/NameCaseConvention.java
  rewrite-core/src/test/kotlin/org/openrewrite/internal/NameCaseConventionTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/RenameLocalVariablesToCamelCase.java
Labels: enhancement

#1195 FindProperties in rewrite-properties missing visitMarkers
  rewrite-properties/src/main/java/org/openrewrite/properties/internal/PropertiesPrinter.java
  rewrite-properties/src/test/kotlin/org/openrewrite/properties/search/FindPropertiesTest.kt
Labels: bug

#1196 FindProperties should have marker on the value, same as yaml and other search results
  rewrite-properties/src/main/java/org/openrewrite/properties/internal/PropertiesPrinter.java
  rewrite-properties/src/main/java/org/openrewrite/properties/search/FindProperties.java
  rewrite-properties/src/test/kotlin/org/openrewrite/properties/search/FindPropertiesTest.kt
Labels: bug

#1182 Relaxed binding on yaml and properties
  rewrite-core/src/main/java/org/openrewrite/internal/NameCaseConvention.java
  rewrite-properties/src/main/java/org/openrewrite/properties/AddProperty.java
  rewrite-properties/src/main/java/org/openrewrite/properties/ChangePropertyKey.java
  rewrite-properties/src/main/java/org/openrewrite/properties/ChangePropertyValue.java
  rewrite-properties/src/main/java/org/openrewrite/properties/DeleteProperty.java
  rewrite-properties/src/main/java/org/openrewrite/properties/search/FindProperties.java
  rewrite-properties/src/test/kotlin/org/openrewrite/properties/ChangePropertyKeyTest.kt
  rewrite-properties/src/test/kotlin/org/openrewrite/properties/ChangePropertyValueTest.kt
  rewrite-properties/src/test/kotlin/org/openrewrite/properties/DeletePropertyTest.kt
  rewrite-properties/src/test/kotlin/org/openrewrite/properties/Issue1020.kt
  rewrite-properties/src/test/kotlin/org/openrewrite/properties/search/FindPropertiesTest.kt
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteProperty.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/search/FindProperty.java
  rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangePropertyKeyTest.kt
  rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/DeletePropertyKeyTest.kt
  rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/search/FindPropertyTest.kt
Labels: enhancement

#1201 NoValueOfOnStringType check for immediate parent being a binary
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoValueOfOnStringType.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/NoValueOfOnStringTypeTest.kt
Labels: bug

#1217 MethodNameCasing should not rename overridden methods
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodNameCasing.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/MethodNameCasingTest.kt
Labels: bug

#1219 MethodMatcher should acknowledge matchOverrides
  rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodName.java
  rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoFinalizer.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/RenameMethodsNamedHashcodeEqualOrTostring.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindDeprecatedMethods.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeMethodNameTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/MethodMatcherTest.kt
Labels: bug, discovery

#1231 Add support to ImportLayoutStyle for specific packages to fold.
  rewrite-java/src/main/java/org/openrewrite/java/RemoveImport.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
  rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
  rewrite-java/src/test/kotlin/org/openrewrite/java/style/ImportLayoutStyleTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/AddImportTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/OrderImportsTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveImportTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveUnusedImportsTest.kt
Labels: enhancement

#1240 ChangeMethodAccessLevel should pass on matchOverrides
  rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodAccessLevel.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeMethodAccessLevelTest.kt
Labels: bug
