Repository openrewrite/rewrite, pull requests merged in 2021-07, with the labels that each got.

#769 String Literal Equality cleanup
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/StringLiteralEquality.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/StringLiteralEqualityTest.kt
Labels: enhancement

#770 No Finalizer cleanup
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoFinalizer.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/NoFinalizerTest.kt
Labels: enhancement

#786 SpacesStyle.withBeforeParentheses.withMethodCall controls spacing on class constructors
  rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/format/SpacesTest.kt
Labels: bug

#814 indexOf should not compare greater than zero [#799]
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/IndexOfShouldNotCompareGreaterThanZero.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/IndexOfShouldNotCompareGreaterThanZeroTest.kt
Labels: design-partner-6, enhancement

#827 String#indexOf and List#indexOf replaceable by contains
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/IndexOfReplaceableByContains.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/IndexOfReplaceableByContainsTest.kt
Labels: enhancement

#817 Refactored Autodetect#ImportLayoutStyleStatistics.
  rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/style/AutodetectTest.kt
Labels: enhancement

#828 Removed unused local variables
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnusedLocalVariables.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedLocalVariablesTest.kt
Labels: design-partner-6, enhancement

#848 Fixing duplicated Checkstyle modules.
  rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java
  rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt
Labels: bug

#840 Remove unused assignments
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnusedAssignments.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedAssignmentsTest.kt
Labels: design-partner-6, enhancement

#855 Remove "remove unused assignment"
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnusedAssignments.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedAssignmentsTest.kt
Labels: bug

#864 UnusedLocalVariable improvements on evaluating left-hand vs right-hand read operations
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnusedLocalVariables.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedLocalVariablesTest.kt
Labels: bug, enhancement

#869 TypeValidator also validates that Identifiers have type information. Fixes #868
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/ChangePackageTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeTypeTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaRecipeTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/PadEmptyForLoopComponentsTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/RenameVariableTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/TypeValidator.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/BooleanChecksNotInvertedTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/MinimumSwitchCasesTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/format/SpacesTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
Labels: enhancement
