Repository openrewrite/rewrite, pull requests merged in 2021-09, with the labels that each got.

#972 ChangeType should allow nested java.lang package imports
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeTypeTest.kt
Labels: bug

#986 Unnecessary space instance creation
  rewrite-hcl/src/main/java/org/openrewrite/hcl/tree/Space.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
  rewrite-json/src/main/java/org/openrewrite/json/tree/Space.java
Labels: bug

#994 Explicitly declare types on lambda arguments
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ExplicitLambdaArgumentTypes.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/ExplicitLambdaArgumentTypesTest.kt
Labels: enhancement

#992 Add OrderPomElements for ordering POM elements per the recommended order
  rewrite-maven/src/main/java/org/openrewrite/maven/OrderPomElements.java
  rewrite-maven/src/test/kotlin/org/openrewrite/maven/OrderPomElementsTest.kt
Labels: enhancement

#1015 Adding `Object.equals` validates argument type recipe for RSPEC-2097
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ObjectEqualsChecksArgumentType.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/ObjectEqualsChecksArgumentTypeTest.kt
Labels: enhancement

#1016 Added clean up recipe for RSPEC-1858.
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoToStringOnStringType.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/NoToStringOnStringTypeTest.kt
Labels: enhancement, design-partner-6

#1017 Add missing override annotations
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/MissingOverrideAnnotation.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/MissingOverrideAnnotationTest.kt
Labels: enhancement

#1022 Use @Language injection "json" rather than javascript for JsonRecipeTest
  rewrite-test/src/main/kotlin/org/openrewrite/json/JsonRecipeTest.kt
Labels: bug

#1021 Yaml and Json XPathMatcher consistent replacement with JsonPathMatcher
  rewrite-json/src/main/java/org/openrewrite/json/ChangeKey.java
  rewrite-json/src/main/java/org/openrewrite/json/ChangeValue.java
  rewrite-json/src/main/java/org/openrewrite/json/DeleteKey.java
  rewrite-json/src/main/java/org/openrewrite/json/JsonPathMatcher.java
  rewrite-json/src/main/java/org/openrewrite/json/search/FindKey.java
  rewrite-json/src/test/kotlin/org/openrewrite/json/ChangeKeyTest.kt
  rewrite-json/src/test/kotlin/org/openrewrite/json/ChangeValueTest.kt
  rewrite-json/src/test/kotlin/org/openrewrite/json/DeleteKeyTest.kt
  rewrite-json/src/test/kotlin/org/openrewrite/json/search/FindKeyByXPathTest.kt
  rewrite-json/src/test/kotlin/org/openrewrite/json/search/FindKeyTest.kt
  rewrite-xml/src/main/java/org/openrewrite/xml/search/FindTags.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangeKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangeValue.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/CopyValue.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/XPathMatcher.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/search/FindKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/search/FindKeyByXPath.java
  rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangeKeyTest.kt
  rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangeValueTest.kt
  rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/CopyValueTest.kt
  rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/DeleteKeyTest.kt
  rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/MergeYamlTest.kt
  rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/XPathMatcherTest.kt
Labels: enhancement

#1034 Fixup BlankLinesVisitor equality checking for the first statement of the block
  rewrite-java/src/main/java/org/openrewrite/java/format/BlankLinesVisitor.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/MissingOverrideAnnotationTest.kt
Labels: bug

#1035 Use postfix counters on for loop induction variables
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ForLoopControlVariablePostfixOperators.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/ForLoopControlVariablePostfixOperatorsTest.kt
Labels: enhancement

#1038 refactor: Add missing `@Override` to overriding and implementing methods
  rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
Labels: enhancement

#1040 Add HCL language annotation to HCLRecipeTest
  rewrite-hcl/src/test/kotlin/org/openrewrite/hcl/format/SpacesTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/hcl/HclRecipeTest.kt
Labels: enhancement

#1039 Added UseJavaInterface recipe to fix code flagged by RSPEC-1319.
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseCollectionInterfaces.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/UseCollectionInterfacesTest.kt
Labels: enhancement, design-partner-6
