Repository openrewrite/rewrite, pull requests merged in 2021-08, with the labels that each got.

#871 [#797] MethodParamPad
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11TreeDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8TreeDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodParamPad.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodParamPadStyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java
  rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTreeCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/MethodParamPadTest.kt
Labels: enhancement

#875 [#797] need braces
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/NeedBraces.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/NeedBracesStyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java
  rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/NeedBracesTest.kt
Labels: enhancement

#876 [#797] TypecastParenPad
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/TypecastParenPad.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/TypecastParenPadStyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java
  rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/TypecastParenPadTest.kt
Labels: enhancement

#886 fix maven repo not being used
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
Labels: bug

#889 [#797] OperatorWrap
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/OperatorWrap.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/OperatorWrapStyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java
  rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/OperatorWrapTest.kt
Labels: enhancement

#892 Fix concurrency issue in recipe test harness
  rewrite-hcl/src/test/kotlin/org/openrewrite/hcl/HclTemplateTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/RecipeTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/AddImportTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeFieldNameTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeFieldTypeTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/InvertConditionTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateSubstitutionsTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/LineCounterTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveImportTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/RenameVariableTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/SameClassNameTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/UseStaticImportTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/format/MinimumViableSpacingTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/format/NormalizeFormatTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/format/WrappingAndBracesTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/search/MaybeUsesImportTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/search/UsesMethodTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/search/UsesTypeTest.kt
  rewrite-xml/src/test/kotlin/org/openrewrite/xml/AddToTagTest.kt
  rewrite-xml/src/test/kotlin/org/openrewrite/xml/ChangeTagValueVisitorTest.kt
  rewrite-xml/src/test/kotlin/org/openrewrite/xml/RemoveContentTest.kt
  rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/format/IndentsTest.kt
Labels: bug

#896 UpgradeDependencyVersion handling of dependencies within dependencyManagement
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
  rewrite-maven/src/test/kotlin/org/openrewrite/maven/UpgradeDependencyVersionTest.kt
Labels: bug

#902 [#797] NoWhitespaceAfter, NoWhitespaceBefore
  rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
  rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoWhitespaceAfter.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoWhitespaceAfterStyle.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoWhitespaceBefore.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoWhitespaceBeforeStyle.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/OperatorWrap.java
  rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java
  rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/NoWhitespaceAfterTest.kt
  rewrite-test/src/main/kotlin/org/openrewrite/java/NoWhitespaceBeforeTest.kt
Labels: enhancement

#916 Support Executions in AddPlugin
  rewrite-maven/src/main/java/org/openrewrite/maven/AddPlugin.java
  rewrite-maven/src/test/kotlin/org/openrewrite/maven/AddPluginTest.kt
Labels: enhancement, design-partner-5

#917 Add DirectScheduler for tests
  rewrite-core/src/main/java/org/openrewrite/scheduling/DirectScheduler.java
  rewrite-test/src/main/kotlin/org/openrewrite/RecipeTest.kt
Labels: enhancement
