Repository openrewrite/rewrite, pull requests merged in 2022-07, with the labels that each got.

#2003 Various fixes in `ChangePackage`
  rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/ChangePackageTest.kt
Labels: design-partner-1

#2013 Added support for `JavaType.Variable` in `ChangePackage`.
  rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/ChangePackageTest.kt
Labels: enhancement

#2052 Guard against null JavaType$Method declaringType in DataFlow models
  rewrite-java/src/main/java/org/openrewrite/java/dataflow/ExternalFlowModels.java
  rewrite-java/src/main/java/org/openrewrite/java/dataflow/ExternalSinkModels.java
Labels: bug

#2057 Cast J to NameTree in visitParameterizedType of JavadocVisitors.
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
Labels: bug

#2059 fix: Update gradle ChangeDependency recipes to allow empty string for config
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyArtifactId.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyGroupId.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyVersion.java
  rewrite-gradle/src/test/kotlin/org/openrewrite/gradle/ChangeDependencyArtifactIdTest.kt
  rewrite-gradle/src/test/kotlin/org/openrewrite/gradle/ChangeDependencyGroupIdTest.kt
  rewrite-gradle/src/test/kotlin/org/openrewrite/gradle/ChangeDependencyVersionTest.kt
Labels: bug

#2048 Print `JavaDoc.LineBreak` in place of new lines in `Space` for @link and @see
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/JavadocVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/Javadoc.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
Labels: bug

#2084 GitProvenance is not correctly deriving the branch name when a local branch does not exist
  rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java
  rewrite-core/src/test/kotlin/org/openrewrite/marker/GitProvenanceTest.kt
Labels: bug
