Repository openrewrite/rewrite, pull requests merged in 2022-01, with the labels that each got.

#1330 fix(rewrite-java): excluding Enum classess from getting serialVersionUid
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/AddSerialVersionUidToSerializable.java
Labels: bug

#1333 [#1332] Configurable array of ignorable variable names in UnusedLocal Variables
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnusedLocalVariables.java
  rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedLocalVariablesTest.kt
Labels: enhancement

#1346 logback 1.0.x -> 1.2.10
  build.gradle.kts
  rewrite-java-8/build.gradle.kts
  rewrite-maven/build.gradle.kts
  rewrite-test/build.gradle.kts
Labels: dependencies
