Repository openrewrite/rewrite, pull requests merged in 2023-07, with the labels that each got.

#3300 Fix NPE caused by org.openrewrite.staticanalysis.CombineSemanticallyEqualCatchBlocks
  rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
Labels: bug

#3384 Allow AddProperty reuse
  rewrite-properties/src/main/java/org/openrewrite/properties/AddProperty.java
Labels: enhancement

#3303 added QualifyThisVisitor
  rewrite-java/src/main/java/org/openrewrite/java/QualifyThisVisitor.java
  rewrite-java/src/test/java/org/openrewrite/java/QualifyThisVisitorTest.java
Labels: recipe

#3392 Add `UpdateMavenWrapper` recipe including checksum verification
  .gitattributes
  rewrite-core/src/main/java/org/openrewrite/Checksum.java
  rewrite-core/src/main/java/org/openrewrite/remote/Remote.java
  rewrite-core/src/main/java/org/openrewrite/remote/RemoteArchive.java
  rewrite-core/src/main/java/org/openrewrite/remote/RemoteFile.java
  rewrite-maven/build.gradle.kts
  rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenWrapper.java
  rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenWrapper.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenWrapperTest.java
  rewrite-maven/src/test/resources/mvnw
  rewrite-maven/src/test/resources/mvnw.cmd
Labels: recipe

#3397 Issue 3275/fix remove used param
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: enhancement

#3408 `UsesMethod` should rely on `TypesInUse`
  rewrite-java/src/main/java/org/openrewrite/java/search/UsesMethod.java
Labels: performance

#3413 Polish Gradle Enterprise recipes names and descriptions
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddGradleEnterpriseGradlePlugin.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddGradleEnterpriseGradlePluginTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtension.java
Labels: enhancement

#3412 Improve OrderImports description
  rewrite-java/src/main/java/org/openrewrite/java/OrderImports.java
Labels: documentation

#3419 Account for Unicode characters in Yaml FormatPreservingReader
  rewrite-core/src/test/java/org/openrewrite/config/ChangeTextToSam.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/FormatPreservingReader.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Labels: bug

#3420 Checking RecipeIntrospectionUtils in rewrite-test
  rewrite-core/src/test/java/org/openrewrite/RecipeSchedulerTest.java
  rewrite-core/src/test/java/org/openrewrite/table/RecipeRunStatsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/ExtractInterfaceTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AssertionsTest.java
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Labels: bug, enhancement

#3424 Improve recipe descriptions
  rewrite-json/src/main/java/org/openrewrite/json/ChangeKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/AppendToSequence.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangeKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyValue.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangeValue.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/CoalesceProperties.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/CommentOutProperty.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/CopyValue.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteProperty.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/cleanup/RemoveUnused.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/search/FindKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/search/FindProperty.java
Labels: documentation

#3427 Turn YAML files with unicode into ParseErrors
  rewrite-yaml/src/main/java/org/openrewrite/yaml/FormatPreservingReader.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Labels: bug

#3428 Migrate moved recipes
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/UpdateMovedPackageClassNameTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/UpdateStaticAnalysisPackageTest.java
  rewrite-java/src/main/resources/META-INF/rewrite/migrate-rewrite.yml
Labels: recipe

#3433 Restore now deprecated constructors pending module migrations
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: bug

#3436 Prevent NPE on null Space of unknown origin
  rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
Labels: bug

#3438 Added unpinned version test
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependency.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/ChangePluginTest.java
Labels: enhancement

#3447 Ensure that system-installed artifacts can be resolved while constructing JavaParser classpath
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Labels: bug, enhancement
