Repository openrewrite/rewrite, pull requests merged in 2023-06, with the labels that each got.

#3284 Recursively init Declarative Recipes
  rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
Labels: bug

#3294 ChangePackage on annotation with FQCN argument
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/internal/TypesInUseTest.java
Labels: bug

#3302 fix: fetch correct maven packaging for purl qualifier
  rewrite-maven/src/main/java/org/openrewrite/maven/utilities/PrintMavenAsCycloneDxBom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/utilities/PrintMavenAsCycloneDxBomTest.java
Labels: bug

#3192 Revert "Revert "Generify `Validated` to `Validated<T>` (#3014)""
  rewrite-core/src/main/java/org/openrewrite/Recipe.java
  rewrite-core/src/main/java/org/openrewrite/Validated.java
  rewrite-core/src/main/java/org/openrewrite/ValidationException.java
  rewrite-core/src/main/java/org/openrewrite/config/DeclarativeNamedStyles.java
  rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
  rewrite-core/src/main/java/org/openrewrite/semver/CaretRange.java
  rewrite-core/src/main/java/org/openrewrite/semver/DependencyMatcher.java
  rewrite-core/src/main/java/org/openrewrite/semver/ExactVersion.java
  rewrite-core/src/main/java/org/openrewrite/semver/HyphenRange.java
  rewrite-core/src/main/java/org/openrewrite/semver/LatestPatch.java
  rewrite-core/src/main/java/org/openrewrite/semver/LatestRelease.java
  rewrite-core/src/main/java/org/openrewrite/semver/Semver.java
  rewrite-core/src/main/java/org/openrewrite/semver/SetRange.java
  rewrite-core/src/main/java/org/openrewrite/semver/TildeRange.java
  rewrite-core/src/main/java/org/openrewrite/semver/XRange.java
  rewrite-core/src/main/java/org/openrewrite/style/NamedStyles.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/Assertions.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyArtifactId.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyClassifier.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyConfiguration.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyExtension.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyGroupId.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/util/GradleWrapper.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/util/GradleWrapperTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodAccessLevel.java
  rewrite-java/src/main/java/org/openrewrite/java/SimplifyMethodChain.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindLiterals.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindText.java
  rewrite-java/src/main/java/org/openrewrite/java/search/HasJavaVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDependencyVisitor.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddManagedDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ExcludeDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveManagedDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeParentVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/search/DependencyInsight.java
  rewrite-maven/src/main/java/org/openrewrite/maven/search/DoesNotIncludeDependency.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddManagedDependencyTest.java
  rewrite-xml/src/main/java/org/openrewrite/xml/security/AddOwaspDateBoundSuppressions.java
  rewrite-xml/src/main/java/org/openrewrite/xml/security/UpdateOwaspSuppressionDate.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java
Labels: enhancement

#3313 Fix/yaml encoding
  rewrite-xml/src/main/java/org/openrewrite/xml/XmlParser.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
Labels: bug

#3311 Tweak style autodetect
  rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java
  rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
  rewrite-xml/src/main/java/org/openrewrite/xml/format/AutoFormatVisitor.java
  rewrite-xml/src/main/java/org/openrewrite/xml/style/Autodetect.java
  rewrite-xml/src/test/java/org/openrewrite/xml/format/AutodetectTest.java
Labels: bug

#3328 Match a dynamic Spring version
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
Labels: bug

#3369 No JsonIdentityInfo on Tree
  rewrite-core/src/main/java/org/openrewrite/Tree.java
Labels: performance

#3355 More accurate type checking
  rewrite-java-test/src/test/java/org/openrewrite/java/FindMissingTypesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/Assertions.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java
Labels: enhancement

#3363 Issue 1698: adding additional checks for internal class imports
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
Labels: bug

#3375 Optimize `LatestVersion#countVersionParts()`
  rewrite-core/src/main/java/org/openrewrite/semver/LatestRelease.java
Labels: enhancement

#3380 Annotate `Tree` and `JavaType` with `@JsonIgnoreProperties`
  rewrite-core/src/main/java/org/openrewrite/Tree.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Labels: performance

#3379 Add array-based `unsafeSet()` methods to `JavaType` implementations
  rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyTypeMapping.java
  rewrite-java/src/main/java/org/openrewrite/java/UnsafeJavaTypeVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Labels: performance

#3372 Refactor `MethodMatcher#matchesTargetType`
  rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: enhancement
