Repository openrewrite/rewrite, pull requests merged in 2023-05, with the labels that each got.

#3190 Update BuildTool marker with wrapper version changes
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
Labels: enhancement

#3195 Add tests to cover additional cases: fully qualified names
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveAnnotationTest.java
Labels: bug

#3204 ChangePackage skipped on FQCN annotation arguments
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java
Labels: bug

#3207 Show diff on RewriteTest comparison failures
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Labels: enhancement

#3214 AppendToSequence twice skips one
  rewrite-yaml/build.gradle.kts
  rewrite-yaml/src/test/java/org/openrewrite/yaml/AppendToSequenceTest.java
Labels: bug

#3218 feat: add visit for constructor calls (#3217)
  rewrite-java-test/src/test/java/org/openrewrite/java/DeleteMethodArgumentTest.java
  rewrite-java/src/main/java/org/openrewrite/java/DeleteMethodArgument.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: enhancement

#3155 Add sporadically failing multi-module ChangeParentPom tests
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Labels: bug

#3242 Support 21-ea as value for java.version in JavaParser
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Labels: bug

#3211 fix: parse environment properties in maven repositories
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepository.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Labels: enhancement

#3226 Fixes #3144 RenamePropertyKey and ChangePropertyValue running together
  rewrite-maven/src/main/java/org/openrewrite/maven/RenamePropertyKey.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RenamePropertyKeyTest.java
Labels: bug

#3244 Fix NoClassDefFoundError in RewriteTest on jgit diff()
  rewrite-test/build.gradle.kts
Labels: bug

#3238 Feature/gradle/enhance update java compatibility
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeJavaCompatibility.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateJavaCompatibility.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeJavaCompatibilityTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateJavaCompatibilityTest.java
Labels: enhancement

#3246 Handle assignments in Gradle extra properties
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Labels: bug

#3245 JavaParser classpath from byte array has issue with default package
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
  rewrite-java-test/src/test/resources/javaparser-byte-array-tests/InterfaceB.class
  rewrite-java-test/src/test/resources/javaparser-byte-array-tests/InterfaceB.java
  rewrite-java-test/src/test/resources/javaparser-byte-array-tests/example/InterfaceA.class
  rewrite-java-test/src/test/resources/javaparser-byte-array-tests/example/InterfaceA.java
Labels: bug

#3233 Add options to the Add Gradle Enterprise Maven recipe
  rewrite-maven/src/main/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtension.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtensionTest.java
Labels: enhancement

#3249 Support default package in `JavaParser.Builder.classpath(byte[][])`
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
Labels: bug

#3251 Compare XML tag names for equality
  rewrite-xml/src/main/java/org/openrewrite/xml/SemanticallyEqual.java
  rewrite-xml/src/test/java/org/openrewrite/xml/SemanticallyEqualTest.java
Labels: bug

#3263 Update Gradle model on removal of dependency
  rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveDependency.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveDependencyTest.java
Labels: enhancement

#3269 Recipe to remove an xml element
  rewrite-xml/src/main/java/org/openrewrite/xml/RemoveXmlTag.java
  rewrite-xml/src/test/java/org/openrewrite/xml/RemoveXmlTagTest.java
Labels: recipe

#3271 added a failing test in ChangeFieldNameTest
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeFieldNameTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeFieldName.java
Labels: bug

#3265 Support using different configurations for different test source sets when adding gradle dependency
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/Assertions.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
  rewrite-java/src/main/java/org/openrewrite/java/Assertions.java
Labels: enhancement

#3281 Fix for type cast error in Gradle AddDependency recipe.
  rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
Labels: bug
