Repository openrewrite/rewrite, pull requests merged in 2023-01, with the labels that each got.

#2616 Change plugin "flags" to Strings to support property placeholders
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Plugin.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/RawPomTest.java
Labels: bug

#2622 Don't lose the license comment
  rewrite-gradle/src/main/java/org/openrewrite/gradle/GradleParser.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/GradleParserTest.java
Labels: bug

#2632 Add Pom model version and cache invalidation for version mismatch
  rewrite-maven/src/main/java/org/openrewrite/maven/cache/RocksdbMavenPomCache.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/cache/RocksdbMavenCacheTest.java
Labels: enhancement

#2633 Fix issue with configuring rewrite-java-* Gradle projects
  rewrite-java-11/build.gradle.kts
  rewrite-java-17/build.gradle.kts
  rewrite-java-8/build.gradle.kts
  settings.gradle.kts
Labels: enhancement

#2646 Add Official Gradle Wrapper Validation Action
  .github/workflows/gradle-wrapper-validation.yml
Labels: enhancement

#2645 build: update gradle wrapper to 7.6
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  rewrite-java-11/build.gradle.kts
  rewrite-java-17/build.gradle.kts
  rewrite-java-8/build.gradle.kts
Labels: enhancement

#2657 Introduce tree visiting hierarchy printer
  rewrite-java/src/main/java/org/openrewrite/java/TreeVisitingPrinter.java
Labels: enhancement

#2663 Introduce finalize private field recipe
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizeLocalVariablesTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizePrivateFieldsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizePrivateFields.java
Labels: enhancement

#2634 Change maven model flags to strings to support property placeholders
  rewrite-gradle/src/test/java/org/openrewrite/gradle/search/DependencyInsightTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenSettings.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawRepositories.java
  rewrite-maven/src/main/java/org/openrewrite/maven/table/MavenMetadataFailures.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Dependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepository.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepositoryMirror.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenDependencyFailuresTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeParentVersionTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/cache/RocksdbMavenCacheTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Labels: enhancement

#2688 Fix an uncovered case of FinalizePrivateFields with `Lombok` `setter` annotation
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizePrivateFieldsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizePrivateFields.java
Labels: enhancement

#2695 replace redundant println(format()) with printf()
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceRedundantFormatWithPrintfTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceRedundantFormatWithPrintf.java
Labels: recipe

#2701 Add remove plugin support
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/RemoveBuildPlugin.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/RemovePluginVisitor.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/RemoveSettingsPlugin.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/RemoveBuildPluginTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/RemoveSettingsPluginTest.java
Labels: recipe

#2721 Default `MethodNameCasing#renamePublicMethods` to `false`
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/MethodNameCasingTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodNameCasing.java
Labels: enhancement

#2716 `FinalizePrivateFields` also needs to update the `JavaType`
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizePrivateFieldsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizePrivateFields.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Labels: enhancement

#2704 Add RemoveCallsToObjectFinalize
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/RemoveCallsToObjectFinalizeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveCallsToObjectFinalize.java
Labels: recipe

#2690 New `InstanceOfPatternMatch` recipe
  rewrite-java-test/src/test/java/org/openrewrite/java/InstanceOfPatternMatchTest.java
  rewrite-java/src/main/java/org/openrewrite/java/InstanceOfPatternMatch.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: recipe

#2718 Handle instance methods and constructor calls in `ReplaceLambdaWithMethodReference`
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReferenceTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReference.java
Labels: enhancement
