Repository openrewrite/rewrite, pull requests merged in 2023-11, with the labels that each got.

#3642 Fix after visitor cursor propagation
  rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java
  rewrite-core/src/test/java/org/openrewrite/TreeVisitorTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaVisitorTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Labels: bug

#3660 update method type on DeleteMethodArgument
  rewrite-java-test/src/test/java/org/openrewrite/java/DeleteMethodArgumentTest.java
  rewrite-java/src/main/java/org/openrewrite/java/DeleteMethodArgument.java
Labels: enhancement

#3681 Do not skip proto3 files, as it warns about out of date LSTs
  rewrite-protobuf/src/main/java/org/openrewrite/protobuf/ProtoParser.java
  rewrite-protobuf/src/test/java/org/openrewrite/protobuf/ProtoParserTest.java
Labels: enhancement

#3682 CreateTextFile should override files of different type
  rewrite-core/src/main/java/org/openrewrite/text/CreateTextFile.java
  rewrite-test/build.gradle.kts
  rewrite-test/src/test/java/org/openrewrite/text/CreateTextFileTest.java
Labels: bug

#3685 Add BitbucketBuildEnvironment for better progress indicators
  rewrite-core/src/main/java/org/openrewrite/marker/ci/BitbucketBuildEnvironment.java
  rewrite-core/src/main/java/org/openrewrite/marker/ci/BuildEnvironment.java
Labels: enhancement

#3708 Remove default `jar` packaging when using `ChangePackaging`
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangePackaging.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangePackagingTest.java
  rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java
Labels: enhancement

#3387 Replicate `FindAndReplace` `No group with name {name}`
  rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java
  rewrite-core/src/test/java/org/openrewrite/text/FindAndReplaceTest.java
Labels: bug

#3713 Reorder constructor arguments too
  rewrite-java-test/src/test/java/org/openrewrite/java/ReorderMethodArgumentsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ReorderMethodArguments.java
Labels: bug, enhancement

#3652 Support intersection type casts
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeMapping.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeSignatureBuilder.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeSignatureBuilder.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeMapping.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeSignatureBuilder.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeSignatureBuilder.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeCastTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaIsoVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTypeVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/UnsafeJavaTypeVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: bug

#3715 Support optional version selector in ParentPomInsight
  rewrite-maven/src/main/java/org/openrewrite/maven/search/ParentPomInsight.java
  rewrite-maven/src/test/java/org/openrewrite/maven/search/ParentPomInsightTest.java
Labels: enhancement

#3721 fixed possible NPE when required methodPatternChain not provided
  rewrite-java/src/main/java/org/openrewrite/java/SimplifyMethodChain.java
Labels: bug

#3707 Tentative fix for missing "//" operator on `XPathMatcher`
  rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java
  rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
Labels: bug, enhancement

#3724 AutoFormat bug with method parameter alignment when using tabs
  rewrite-java-test/src/test/java/org/openrewrite/java/format/TabsAndIndentsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
Labels: bug

#3725 Update preconditions hint in yaml recipes
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/RemoveApplicabilityTestFromYamlRecipeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/recipes/RemoveApplicabilityTestFromYamlRecipe.java
Labels: enhancement

#3726 Migrate single-source applicability tests to preconditions
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/MigrateJavaTemplateToRewrite8Test.java
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/RemoveApplicabilityTestFromYamlRecipeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/recipes/RemoveApplicabilityTestFromYamlRecipe.java
Labels: enhancement

#3733 Only run recipe a single cycle when possible
  rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
Labels: performance

#3734 Stop over eager exclude of UseStaticImport
  rewrite-java-test/src/test/java/org/openrewrite/java/UseStaticImportTest.java
  rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java
Labels: bug

#3295 Improve the context-free template caching
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
Labels: enhancement

#3448 `ReplaceConstantWithAnotherConstant` fails to replace field annotation arguments
  rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceConstantWithAnotherConstantTest.java
Labels: bug

#3717 [#3716] Test for an IllegalArgumentException in JavaTemplateJava…
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateSubstitutionsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
Labels: bug

#3735 Ensure SourceSpec text blcks start on a new line
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/SourceSpecTextBlockIndentationTest.java
  rewrite-java/src/main/java/org/openrewrite/java/recipes/SourceSpecTextBlockIndentation.java
Labels: enhancement
