Repository openrewrite/rewrite, pull requests merged in 2023-02, with the labels that each got.

#2750 Make `J.ParameterizedType#getType()` return a `JavaType.Parameterized`
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/ImplementInterface.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ExplicitLambdaArgumentTypes.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseCollectionInterfaces.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseLambdaForFunctionalInterface.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindFieldsOfType.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: bug

#2747 Fix `J.Unary` side effects and `SemanticallyEqual`
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/InstanceOfPatternMatchTest.java
  rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: bug

#2762 Fix handling of generics in `InstanceOfPatternMatch`
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/InstanceOfPatternMatchTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ImplementInterface.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/InstanceOfPatternMatch.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoDoubleBraceInitialization.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: bug

#2766 #412 Added Operating System Marker to Rewrite
  rewrite-core/src/main/java/org/openrewrite/marker/OperatingSystem.java
Labels: enhancement

#2782 Add `JavaType.FullyQualified.Kind.RECORD`
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/RemoveUnusedLocalVariablesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Labels: bug

#2741 Enhance the `Space` recipe to support transformation for multiple whitespaces
  rewrite-java-test/src/test/java/org/openrewrite/java/format/SpacesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
Labels: enhancement, design-partner-1

#2784 Fix the replacement coordinates for unary expressions
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/AvoidBoxedBooleanExpressionsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/CoordinateBuilder.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: bug

#2780 Fix a defect of `RewriteTest.rewriteRun()` that cannot detect unexpected newly generated files
  rewrite-core/src/test/java/org/openrewrite/text/AppendToTextFileTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/AddGradleWrapperTest.java
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Labels: bug

#2803 Added recipe to replace Apache validate.notNull with objects.requireN…
  rewrite-java/src/main/resources/META-INF/rewrite/java-best-practices.yml
Labels: enhancement, recipe

#2816 Also validate constructor calls in `RewriteTest` sources
  rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/EmptyBlockTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UseForEachRemoveInsteadOfSetRemoveAllTest.java
  rewrite-java/src/main/java/org/openrewrite/java/Assertions.java
  rewrite-test/src/main/java/org/openrewrite/test/TypeValidation.java
Labels: enhancement

#2815 Fix `IsEmptyCallOnCollections` in for loop control
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/IsEmptyCallOnCollectionsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/IsEmptyCallOnCollections.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
Labels: bug

#2821 Slight performance improvements to Source Positions recipe
  rewrite-java-test/src/test/java/org/openrewrite/java/UpdateSourcePositionsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/UpdateSourcePositions.java
Labels: enhancement

#2827 `UnnecessaryExplicitTypeArguments`: Don't apply to `var` variables
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UnnecessaryExplicitTypeArgumentsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/UnnecessaryExplicitTypeArguments.java
Labels: bug

#2771 Improve the equality check in `ListUtils#flatMap()`
  rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java
  rewrite-core/src/test/java/org/openrewrite/internal/ListUtilsTest.java
Labels: enhancement, performance

#2831 Add missing field type to `instanceof` pattern variables
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
Labels: bug

#2659 feat: fetch latest gradle release if no version is given
  rewrite-gradle/build.gradle.kts
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddGradleWrapper.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/util/GradleWrapper.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/AddGradleWrapperTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/util/GradleWrapperTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/util/package-info.java
  rewrite-gradle/src/test/resources/gradle-7.6-bin.zip.sha256
  rewrite-gradle/src/test/resources/gradle-7.6-wrapper.jar.sha256
Labels: enhancement

#2833 fix: `AddImport` should allow static imports from `java.lang`
  rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
Labels: enhancement

#2828 Recipe/remove instanceof pattern
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/RemoveInstanceOfPatternMatchTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveInstanceOfPatternMatch.java
Labels: recipe

#2836 Add first simple ArchUnit tests
  rewrite-java/build.gradle.kts
  rewrite-java/src/main/java/org/openrewrite/java/ai/package-info.java
  rewrite-java/src/main/java/org/openrewrite/java/table/package-info.java
  rewrite-java/src/test/java/org/openrewrite/java/OpenRewriteArchitectureTest.java
Labels: enhancement

#2798 `MethodParamPad` no longer formats entire method body
  rewrite-core/src/main/java/org/openrewrite/SourceFile.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/format/OmitParenthesesFormat.java
  rewrite-java-test/src/test/java/org/openrewrite/java/MethodParamPadTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodParamPad.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/TypecastParenPad.java
  rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
Labels: enhancement

#2825 First draft of JSON schema for OpenRewrite resources
  rewrite-core/openrewrite.json
Labels: documentation

#2841 Add recipe to replace text blocks with strings
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceTextBlockWithStringTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceTextBlockWithString.java
Labels: recipe

#2789 Java parser partial reset
  rewrite-java-11/src/main/java/org/openrewrite/java/Java11Parser.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
  rewrite-java-17/src/main/java/org/openrewrite/java/Java17Parser.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
  rewrite-java-8/src/main/java/org/openrewrite/java/Java8Parser.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Labels: enhancement

#2802 Allow Recipes to influence later Recipe Applicability
  rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
  rewrite-core/src/main/java/org/openrewrite/filter/RecipeApplicableTest.java
  rewrite-core/src/main/java/org/openrewrite/filter/RecipeSingleSourceApplicableTest.java
  rewrite-core/src/main/java/org/openrewrite/filter/package-info.java
  rewrite-java-test/src/test/java/org/openrewrite/java/filter/SourceApplicabilityFilterTest.java
  rewrite-java/src/main/java/org/openrewrite/java/filter/SourceApplicabilityFilter.java
Labels: enhancement

#2842 Add recipe to replace Stream.toList() with Stream.collect()
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceStreamToListWithCollectTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceStreamToListWithCollect.java
Labels: recipe

#2878 Update the CodeQL data flow models
  rewrite-java/src/main/java/org/openrewrite/java/dataflow/ExternalFlowModels.java
  rewrite-java/src/main/java/org/openrewrite/java/dataflow/ExternalSinkModels.java
  rewrite-java/src/main/java/org/openrewrite/java/dataflow/internal/csv/CsvLoader.java
  rewrite-java/src/main/resources/data-flow/README.md
  rewrite-java/src/main/resources/data-flow/model.csv
  rewrite-java/src/main/resources/data-flow/sinks.csv
Labels: enhancement

#2844 Recipe: chain StringBuilder append calls
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ChainStringBuilderAppendCallsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/TreeVisitingPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ChainStringBuilderAppendCalls.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceTextBlockWithString.java
Labels: recipe

#2895 recipe: Replace deprecated `Runtime.Exec()` methods
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceDeprecatedRuntimeExecMethodsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ChainStringBuilderAppendCalls.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceDeprecatedRuntimeExecMethods.java
Labels: recipe

#2896 Prevent bubbling of error on Groovy compilation phase completion
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/CompilationUnitTest.java
Labels: enhancement

#2890 Remove the gradle-api from being shaded into rewrite-gradle.
  rewrite-gradle/build.gradle.kts
  rewrite-gradle/src/main/java/org/openrewrite/gradle/Assertions.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/GradleParser.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Labels: enhancement
