Repository openrewrite/rewrite, pull requests merged in 2023-08, with the labels that each got.

#3451 Take license header into account when adding gradle plugin
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddBuildPluginTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddGradleEnterpriseGradlePluginTest.java
Labels: bug

#3452 fixed valid values and docs for Gradle Enterprise recipes
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddGradleEnterpriseGradlePlugin.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtension.java
Labels: bug

#3455 Fix CRLF newlines in AddImport
  rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
Labels: bug, test provided

#3331 Drop BuildToolFailure marker, recipe and table
  rewrite-core/src/main/java/org/openrewrite/FindBuildToolFailures.java
  rewrite-core/src/main/java/org/openrewrite/marker/BuildToolFailure.java
  rewrite-core/src/main/java/org/openrewrite/table/BuildToolFailures.java
  rewrite-core/src/test/java/org/openrewrite/FailureLogAnalyzerTest.java
Labels: enhancement

#3460 Add Maven dependency before only comments in <dependencies>
  rewrite-maven/build.gradle.kts
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/InsertDependencyComparator.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
Labels: bug

#3459 Require parse-to-print idempotence
  rewrite-core/src/main/java/org/openrewrite/ExecutionContext.java
  rewrite-core/src/main/java/org/openrewrite/Parser.java
  rewrite-core/src/main/java/org/openrewrite/SourceFile.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/search/DependencyInsight.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/HclParser.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
  rewrite-json/src/main/java/org/openrewrite/json/JsonParser.java
  rewrite-maven/src/main/java/org/openrewrite/maven/table/DependencyGraph.java
  rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java
  rewrite-protobuf/src/main/java/org/openrewrite/protobuf/ProtoParser.java
  rewrite-xml/src/main/java/org/openrewrite/xml/XmlParser.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/AppendToSequenceTest.java
Labels: enhancement, design-partner-3

#3465 Added ChangeNamespaceValue recipe and tests
  rewrite-xml/src/main/java/org/openrewrite/xml/ChangeNamespaceValue.java
  rewrite-xml/src/test/java/org/openrewrite/xml/ChangeNamespaceValueTest.java
Labels: recipe

#3466 Add `JavaSourceFile#service(Class)` and `ImportService`
  rewrite-java-test/src/test/java/org/openrewrite/java/ShortenFullyQualifiedTypeReferencesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ExtractInterface.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/recipes/MigrateRecipeToRewrite8.java
  rewrite-java/src/main/java/org/openrewrite/java/service/ImportService.java
  rewrite-java/src/main/java/org/openrewrite/java/service/package-info.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaSourceFile.java
Labels: enhancement

#3472 Add `maybeAddImport(String, String, String, boolean)`
  rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/service/ImportService.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: enhancement

#3476 Rely on parser to catch print inequality
  rewrite-yaml/src/main/java/org/openrewrite/yaml/FormatPreservingReader.java
Labels: enhancement

#3474 Add columns for type and method to `MethodCalls` datatable produced by `FindMethods`
  rewrite-java-test/src/test/java/org/openrewrite/java/search/FindMethodsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindMethods.java
  rewrite-java/src/main/java/org/openrewrite/java/table/MethodCalls.java
Labels: enhancement

#3484 Fix a bug of last comment suffix
  rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
  rewrite-java/src/test/java/org/openrewrite/java/tree/SpaceTest.java
Labels: bug

#3486 Changing method type in ReorderMethodArguments
  rewrite-java-test/src/test/java/org/openrewrite/java/ReorderMethodArgumentsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ReorderMethodArguments.java
Labels: bug

#3490 Allow rewrite-static-analysis to reuse `SimplifyBooleanExpressionVisitor`
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitor.java
Labels: enhancement

#3492 Do not trim actual either with no trim
  rewrite-core/src/main/java/org/openrewrite/text/CreateTextFile.java
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
  rewrite-test/src/test/java/org/openrewrite/text/CreateTextFileTest.java
Labels: bug

#3493 Fix typos
  README.md
Labels: documentation

#3487 Fix AddGradleEnterpriseMavenExtension optional version to get the latest
  rewrite-maven/src/main/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtension.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtensionTest.java
Labels: bug

#3498 Use tag groupId and artifactId to change version
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradePluginVersionTest.java
Labels: bug

#3481 Upgrade Maven plugin dependencies
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
Labels: enhancement

#3499 Make `Space#flyweights` synchronized once again
  rewrite-hcl/src/main/java/org/openrewrite/hcl/tree/Space.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
  rewrite-json/src/main/java/org/openrewrite/json/tree/Space.java
  rewrite-protobuf/src/main/java/org/openrewrite/protobuf/tree/Space.java
  tools/language-parser-builder/src/main/java/org/openrewrite/toml/tree/Space.java
Labels: enhancement, question

#3503 Add `AbstractRefasterJavaVisitor`
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/AbstractRefasterJavaVisitor.java
Labels: enhancement

#3505 Delay the resolution of classpath in `JavaParser.Builder`
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
  rewrite-java-11/src/main/java/org/openrewrite/java/Java11Parser.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
  rewrite-java-17/src/main/java/org/openrewrite/java/Java17Parser.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
  rewrite-java-8/src/main/java/org/openrewrite/java/Java8Parser.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Labels: performance

#3506 Standardize line break recipe name
  rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeLineBreaks.java
Labels: enhancement

#3517 RewriteTest / YamlResourceLoader Enhancements
  rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
  rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
  rewrite-core/src/main/java/org/openrewrite/config/Environment.java
  rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
  rewrite-core/src/main/java/org/openrewrite/internal/lang/NullUtils.java
  rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java
  rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java
  rewrite-core/src/test/resources/META-INF/rewrite/test-sample-a.yml
  rewrite-core/src/test/resources/META-INF/rewrite/test-sample-b.yml
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddSettingsPluginRepository.java
  rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java
Labels: enhancement
