Repository openrewrite/rewrite, pull requests merged in 2023-09, with the labels that each got.

#3524 Recipe validation / RecipeIntrospectionUtils changes for String fields
  rewrite-core/src/main/java/org/openrewrite/internal/RecipeIntrospectionUtils.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
  rewrite-properties/src/main/java/org/openrewrite/properties/AddProperty.java
Labels: bug

#3521 fix: use source file encoding for reading parser input (#3520)
  rewrite-core/src/main/java/org/openrewrite/SourceFile.java
  rewrite-core/src/test/java/org/openrewrite/SourceFileTest.java
Labels: bug

#3515 Added new recipe to change project version of a maven project.
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeProjectVersion.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeProjectVersionTest.java
Labels: recipe, Ready For Review

#3542 Add 409 and other non retryable status codes to isClientSideException()
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
Labels: enhancement, performance

#3541 Prevent NPE on `namedStyle.styles.iterator()`
  rewrite-core/src/main/java/org/openrewrite/style/NamedStyles.java
Labels: bug

#3544 Fix issue with duplicate `relativePath` on `ChangeParentPom`
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenTagInsertionComparator.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
Labels: bug

#3538 AddPlugin changes; make `version` optional and add `filePattern`
  rewrite-maven/src/main/java/org/openrewrite/maven/AddPlugin.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddPluginTest.java
Labels: enhancement

#3556 Remove uses of `String#toCharArray()`
  rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/format/BlankLinesVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeLineBreaksVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeTabsOrSpacesVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/format/RemoveTrailingWhitespaceVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
Labels: performance

#3557 Show warnings in `MavenDownloadingExceptions` previously in `UncheckedMavenDownloadingException`
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UncheckedMavenDownloadingException.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenDependencyFailuresTest.java
Labels: bug, enhancement

#3577 Handle varargs in `ReloadableJava17JavadocVisitor`
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
Labels: bug

#3581 Drop prefixless expressions in POM
  rewrite-maven/src/main/resources/META-INF/rewrite/maven.yml
  rewrite-maven/src/test/java/org/openrewrite/maven/maven4/PrefixlessExpressionsTest.java
Labels: recipe

#3583 Maven parent POM insight through data table
  rewrite-maven/src/main/java/org/openrewrite/maven/search/ParentPomInsight.java
  rewrite-maven/src/main/java/org/openrewrite/maven/table/ParentPomsInUse.java
  rewrite-maven/src/test/java/org/openrewrite/maven/search/ParentPomInsightTest.java
Labels: recipe
