Repository openrewrite/rewrite, pull requests merged in 2023-12, with the labels that each got.

#3748 Added quoted marker to represent escaped identifiers.
  rewrite-java/src/main/java/org/openrewrite/java/marker/Quoted.java
Labels: parser-kotlin

#3749 Change HasSourcePath from a Visitor into a Recipe for use in yaml preconditions
  rewrite-core/src/main/java/org/openrewrite/HasSourcePath.java
  rewrite-core/src/main/java/org/openrewrite/text/ChangeText.java
  rewrite-core/src/main/java/org/openrewrite/text/Find.java
  rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java
  rewrite-core/src/main/java/org/openrewrite/text/FindMultiselect.java
  rewrite-core/src/test/java/org/openrewrite/RecipeBasicsTest.java
  rewrite-core/src/test/java/org/openrewrite/config/ChangeTextToSam.java
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/MigrateRecipeToRewrite8Test.java
  rewrite-test/src/test/java/org/openrewrite/HasSourcePathTest.java
  rewrite-xml/src/main/java/org/openrewrite/xml/RemoveXmlTag.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/CopyValueTest.java
Labels: enhancement

#3613 Added Recipe for removing Empty XML tags
  rewrite-xml/src/main/java/org/openrewrite/xml/RemoveContentVisitor.java
  rewrite-xml/src/main/java/org/openrewrite/xml/RemoveEmptyXmlTags.java
  rewrite-xml/src/test/java/org/openrewrite/xml/RemoveEmptyXmlTagsTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/RemoveXmlTagTest.java
Labels: recipe

#3662 Restrict UseStaticImport to static methods (#3661)
  rewrite-java-test/src/test/java/org/openrewrite/java/UseStaticImportTest.java
  rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java
Labels: bug

#3758 Drop HasSourcePath in favor of FindSourceFiles
  rewrite-core/src/main/java/org/openrewrite/HasSourcePath.java
  rewrite-core/src/main/java/org/openrewrite/PathUtils.java
  rewrite-core/src/main/java/org/openrewrite/text/ChangeText.java
  rewrite-core/src/main/java/org/openrewrite/text/Find.java
  rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java
  rewrite-core/src/main/java/org/openrewrite/text/FindMultiselect.java
  rewrite-core/src/test/java/org/openrewrite/PathUtilsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/MigrateRecipeToRewrite8Test.java
  rewrite-test/src/test/java/org/openrewrite/FindSourceFilesTest.java
  rewrite-test/src/test/java/org/openrewrite/HasSourcePathTest.java
  rewrite-xml/src/main/java/org/openrewrite/xml/RemoveXmlTag.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/CopyValueTest.java
Labels: enhancement

#3753 Added support for escaped identifiers to TypeTree.build.
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeTree.java
Labels: parser-kotlin

#3767 Allow FindAndReplace to remove matches
  rewrite-core/src/main/java/org/openrewrite/marker/AlreadyReplaced.java
  rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java
  rewrite-core/src/test/java/org/openrewrite/text/FindAndReplaceTest.java
Labels: enhancement

#3769 Replace `org.junit.platform.commons.util.StringUtils` with `org.openrewrite.internal.StringUtils`
  rewrite-properties/src/main/java/org/openrewrite/properties/CreatePropertiesFile.java
  rewrite-xml/src/main/java/org/openrewrite/xml/CreateXmlFile.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/CreateYamlFile.java
Labels: bug

#3771 `AddPropery` now accepts a comment
  rewrite-core/src/main/java/org/openrewrite/internal/lang/NullUtils.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddProperty.java
  rewrite-properties/src/main/java/org/openrewrite/properties/AddProperty.java
  rewrite-properties/src/test/java/org/openrewrite/properties/AddPropertyTest.java
Labels: enhancement

#3793 Fix for AddPlugin when plugin version is managed
  rewrite-maven/src/main/java/org/openrewrite/maven/AddPlugin.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddPluginTest.java
Labels: bug

#3794 Skip updating Gradle when already updated
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
Labels: enhancement

#3795 Find JavaVersion markers on any source file
  rewrite-java-test/src/test/java/org/openrewrite/java/search/HasJavaVersionTest.java
  rewrite-java/src/main/java/org/openrewrite/java/search/HasJavaVersion.java
Labels: bug, enhancement

#3798 Skip nested classes for document examples
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/SelectRecipeExamplesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/recipes/SelectRecipeExamples.java
Labels: enhancement

#3802 Improve diagnostics on RawPom parse failures
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
Labels: enhancement

#3813 Handle XML escapes in tag values
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
  rewrite-xml/build.gradle.kts
  rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java
Labels: bug, parser-xml

#3814 switch around mkdirs exists to avoid race condition
  rewrite-java/src/main/java/org/openrewrite/java/JavaParserExecutionContextView.java
Labels: bug

#3819 Include Recipe class simple name in validation errors
  rewrite-core/src/main/java/org/openrewrite/Recipe.java
Labels: enhancement

#3822 Maven POM downloader optimizations
  rewrite-maven/src/main/java/org/openrewrite/maven/cache/InMemoryMavenPomCache.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepository.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepositoryMirror.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Labels: enhancement

#3823 filePattern on FindSourceFiles is now nullable, and matches all files…
  rewrite-core/src/main/java/org/openrewrite/FindSourceFiles.java
  rewrite-test/src/test/java/org/openrewrite/FindSourceFilesTest.java
  rewrite-xml/src/main/java/org/openrewrite/xml/RemoveXmlTag.java
Labels: enhancement

#3812 Add `J.NullableType` for Kotlin / C#
  rewrite-java/src/main/java/org/openrewrite/java/JavaIsoVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JRightPadded.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
Labels: parser-kotlin, parser-c#

#3768 added plugins to ResolvedPom + some tests
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: enhancement

#3841 Revert "The `managedReference` fields are no longer required"
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Labels: bug

#3844 Replace resilience4j with failsafe
  rewrite-maven/build.gradle.kts
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenArtifactDownloader.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Labels: dependencies

#3834 Add utility to print recipe tree
  rewrite-test/src/main/java/org/openrewrite/test/RecipePrinter.java
  rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
  rewrite-test/src/test/java/org/openrewrite/test/RecipePrinterTest.java
Labels: enhancement

#3850 Correctly handle `Recipe#maxCycles()` in `RecipeStack`
  rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeStack.java
  rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java
  rewrite-test/src/main/java/org/openrewrite/test/AdHocRecipe.java
Labels: bug

#3833 Problem parsing unknown Javadoc tag
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaIsoVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/marker/LeadingBrace.java
Labels: bug, parser-java

#3848 Added ArrayTypeTree and support for annotated dimensions of array types.
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodDeclarationTest.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/AnnotationTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ArrayTypeTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/MethodInvocationTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/search/FindTypesTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/service/AnnotationServiceTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/format/NoWhitespaceAfter.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindTypes.java
  rewrite-java/src/main/java/org/openrewrite/java/service/AnnotationService.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: parser-java

#3864 Correctly deduplicate managed dependencies using classifier
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveDuplicateDependenciesTest.java
Labels: bug

#3865 Minor revision to ArrayType#create to account for types on J.ArrayType from old Groovy LSTs.
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: parser-java
