Repository openrewrite/rewrite, pull requests merged in 2023-04, with the labels that each got.

#2991 Add `JavaTemplate.Matcher`
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplateSemanticallyEqual.java
Labels: enhancement

#3086 Allow upgrading non-semver Maven dependencies
  rewrite-core/src/main/java/org/openrewrite/semver/Semver.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
Labels: enhancement

#3092 Add support for parsing Groovy StaticMethodCallExpression statements
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
Labels: enhancement

#3067 Correctly handle the many ways to describe a root source file
  rewrite-core/src/main/java/org/openrewrite/FindSourceFiles.java
  rewrite-core/src/main/java/org/openrewrite/PathUtils.java
  rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java
  rewrite-core/src/test/java/org/openrewrite/PathUtilsTest.java
  rewrite-core/src/test/java/org/openrewrite/internal/StringUtilsTest.java
  rewrite-test/src/test/java/org/openrewrite/FindSourceFilesTest.java
Labels: bug

#3105 Remove automatic source set addition to compilation units
  rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/Assertions.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java
  rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/OrderImportsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/MethodNameCasingTest.java
  rewrite-java/src/main/java/org/openrewrite/java/Assertions.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
  rewrite-test/src/main/java/org/openrewrite/test/SourceSpec.java
Labels: enhancement

#2942 new YAML recipe: AppendToSequence
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/AppendToSequence.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/AppendToSequenceVisitor.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/AppendToSequenceTest.java
Labels: recipe

#3119 Unwrap when if condition is a single parenthesized expression
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesVisitor.java
Labels: enhancement

#3137 New recipe to utilise ChangeTagValueVisitor capabilities for general XML files
  rewrite-xml/src/main/java/org/openrewrite/xml/ChangeTagValue.java
Labels: recipe

#3151 remove semicolons from RemoveUnusedVisitorTest
  rewrite-yaml/src/test/java/org/openrewrite/yaml/cleanup/RemoveUnusedVisitorTest.java
Labels: enhancement

#3153 MavenPomDownloader support download snapshot timestamp version
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Labels: bug

#3150 ClasspathScanningLoader should catch Throwable not Exception to catch Error
  rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
Labels: enhancement

#3162 NoStaticImport recipe updates inner calls #3161
  rewrite-java-test/src/test/java/org/openrewrite/java/NoStaticImportTest.java
  rewrite-java/src/main/java/org/openrewrite/java/NoStaticImport.java
Labels: bug

#3166 Add FindRepository and AddSettingsPluginRepository recipes for Gradle
  rewrite-gradle/src/main/groovy/RepositoryHandler.groovy
  rewrite-gradle/src/main/groovy/RewriteGradleProject.groovy
  rewrite-gradle/src/main/groovy/RewriteSettings.groovy
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddSettingsPluginRepository.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/search/FindRepository.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddSettingsPluginRepositoryTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/search/FindRepositoryTest.java
Labels: recipe

#3165 NoStaticImport recipe updates getClass calls
  rewrite-java-test/src/test/java/org/openrewrite/java/NoStaticImportTest.java
  rewrite-java/src/main/java/org/openrewrite/java/NoStaticImport.java
Labels: bug

#3174 CONTRIBUTING.md need JDK8 and gradle remark
  CONTRIBUTING.md
Labels: enhancement
