Repository openrewrite/rewrite, pull requests merged in 2023-03, with the labels that each got.

#2921 Fix substitution for anonymous class
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
Labels: bug

#2910 report NoWhitespaceAfter bug
  rewrite-java-test/src/test/java/org/openrewrite/java/NoWhitespaceAfterTest.java
Labels: bug

#2923 Load Gradle API from classpath resources when it is unavailable in th…
  rewrite-gradle/build.gradle.kts
  rewrite-gradle/src/main/java/org/openrewrite/gradle/GradleParser.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
Labels: enhancement

#2925 Fix string to map notation conversion. Fixes gh-2805
  rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseMapNotation.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/DependencyUseMapNotationTest.java
Labels: bug

#2926 Properly type-attribute `#{any()}` template parameters
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceRedundantFormatWithPrintfTest.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
Labels: bug

#2863 Support `instanceof` pattern variables in `JavaTemplate`
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateInstanceOfTest.java
  rewrite-java/build.gradle.kts
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/PatternVariables.java
  rewrite-java/src/test/java/org/openrewrite/java/internal/template/PatternVariablesTest.java
Labels: bug

#2894 Added ReplaceStringLiteralWithConstant recipe
  rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceStringLiteralWithConstantTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ReplaceStringLiteralWithConstant.java
Labels: recipe

#2941 Guard against empty strings
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java
Labels: bug

#2943 Allow matching an LST subtree against a `JavaTemplate`
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
  rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: enhancement

#2959 Add a new `@Primitive` annotation for `JavaTemplate#compile()`
  rewrite-java/src/main/java/org/openrewrite/java/template/Primitive.java
  rewrite-java/src/main/java/org/openrewrite/java/template/package-info.java
Labels: enhancement

#2952 Added Maven/DoesNotIncludeDependency generic applicability test
  rewrite-maven/src/main/java/org/openrewrite/maven/search/DependencyInsight.java
  rewrite-maven/src/main/java/org/openrewrite/maven/search/DoesNotIncludeDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/search/FindDependency.java
  rewrite-maven/src/test/java/org/openrewrite/maven/search/DependencyInsightTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/search/DoesNotIncludeDependencyTest.java
Labels: recipe

#2944 Added `acceptTransitive` flag to AddDependency, default false. Also f…
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
Labels: enhancement

#2969 Allow tests to configure default Java version for sources
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceTextBlockWithStringTest.java
  rewrite-java/src/main/java/org/openrewrite/java/Assertions.java
  rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
  rewrite-test/src/main/java/org/openrewrite/test/SourceSpec.java
Labels: enhancement

#2983 Maven ChangePropertyKey
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangePropertyKey.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangePropertyKeyTest.java
  rewrite-xml/src/main/java/org/openrewrite/xml/ChangeTagNameVisitor.java
Labels: recipe

#2992 fix: merge new entry into existing mapping (#2881)
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYamlVisitor.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/ChangePropertyKeyTest.java
Labels: bug

#3000 Fix static import autodetection when imports come first and in multip…
  rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java
  rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
Labels: bug

#3003 Make AddGradleEnterprise react to the current Gradle version. Fixes g…
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddGradleEnterprise.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddGradleEnterpriseTest.java
Labels: enhancement

#3006 Switch to doNext so that applicability tests are correctly utilized
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddGradleEnterprise.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddGradleEnterpriseTest.java
Labels: enhancement

#3008 Rework tooling api for `RewriteTest` in order to make it more complete
  rewrite-gradle/src/main/java/org/openrewrite/gradle/Assertions.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/AddPropertyTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeLiteralDependencyVersionTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddGradleEnterpriseTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/search/DependencyInsightTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/search/FindGradleProjectTest.java
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Labels: enhancement

#3021 Fix bug in parsing of switch statements in `G` island grammar
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/SwitchTest.java
Labels: bug

#3023 Support version ranges in parent reference
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: bug

#3024 Recipe instances now store their `RecipeDescriptor` to avoid cost of …
  rewrite-core/src/main/java/org/openrewrite/Recipe.java
  rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
  rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
  rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
  rewrite-core/src/main/java/org/openrewrite/internal/RecipeIntrospectionUtils.java
  rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java
  rewrite-core/src/test/java/org/openrewrite/config/YamlResourceLoaderTest.java
Labels: enhancement

#3010 Do not rely on Path.toUri().getPath()
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserInputFileObject.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserInputFileObject.java
  rewrite-java-8/src/main/java/org/openrewrite/java/Java8ParserInputFileObject.java
Labels: bug

#3038 #2950 Preserve parentheses around binary operations
  rewrite-java-test/src/test/java/org/openrewrite/java/UnwrapParenthesesTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/EqualsAvoidsNullTest.java
  rewrite-java/src/main/java/org/openrewrite/java/UnwrapParentheses.java
Labels: bug, enhancement

#3041 Execute lookup for declaring scope instead of parent scope
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizeLocalVariablesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizeLocalVariables.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: enhancement

#3037 Added replace constant with another constant recipe.
  rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceConstantWithAnotherConstantTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ReplaceConstantWithAnotherConstant.java
Labels: recipe

#3045 #2940 optional literal value for replacement
  rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceStringLiteralWithConstantTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ReplaceStringLiteralWithConstant.java
Labels: enhancement

#3059 Fix `tabsize` inaccurate issue
  rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java
  rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
Labels: bug

#3060 Add guard for empty settings.gradle file
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddSettingsPluginTest.java
Labels: bug
