Repository openrewrite/rewrite, pull requests merged in 2023-10, with the labels that each got.

#3591 Add explicit Maven plugin groupId for clarity
  rewrite-maven/src/main/java/org/openrewrite/maven/cleanup/ExplicitPluginGroupId.java
  rewrite-maven/src/main/resources/META-INF/rewrite/maven.yml
  rewrite-maven/src/test/java/org/openrewrite/maven/cleanup/ExplicitPluginGroupIdTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/cleanup/ManagedDependencyRequiresVersionTest.java
Labels: recipe

#3600 Merge NormalizeMavenVariables into PrefixlessExpressions
  rewrite-maven/src/main/java/org/openrewrite/maven/NormalizeMavenVariables.java
  rewrite-maven/src/main/java/org/openrewrite/maven/RenamePropertyKey.java
  rewrite-maven/src/main/resources/META-INF/rewrite/maven.yml
  rewrite-maven/src/test/java/org/openrewrite/maven/NormalizeMavenVariablesTest.java
Labels: enhancement

#3629 RemoveUnusedImports conflicts with Record
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
Labels: bug

#3634 Fixed property usage pattern matching search results
  rewrite-maven/src/main/java/org/openrewrite/maven/search/FindProperties.java
  rewrite-maven/src/test/java/org/openrewrite/maven/search/FindPropertiesTest.java
Labels: bug

#3638 Remove unused annotation parameter imports
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveAnnotationTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveAnnotationVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/Expression.java
Labels: enhancement

#3592 Add explicit Maven plugin version for reproducibility
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenTagInsertionComparator.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/cleanup/ExplicitPluginVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/main/resources/META-INF/rewrite/maven.yml
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradePluginVersionTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/cleanup/ExplicitPluginVersionTest.java
Labels: recipe

#3644 Exclude `ResolvedDependency#dependencies` in `hashCode()`
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedDependency.java
Labels: bug

#3609 RecipeSpec recipe caching
  rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java
Labels: enhancement, performance

#3646 fixed inner class
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Labels: bug

#3564 Type validation for before sources in `RewriteTest`
  rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/tree/TaskTest.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/JavaParserTypeMappingTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/MinimumJava11.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/BinaryTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ForEachLoopTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ForLoopTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/InstanceOfTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/LambdaTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/MemberReferenceTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/NewClassTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeParameterAndWildcardTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/VariableDeclarationsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateInstanceOfTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/MethodMatcherTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/UnwrapParenthesesTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/format/MethodParamPadTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/format/NoWhitespaceBeforeTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/format/TabsAndIndentsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/MigrateJavaTemplateToRewrite8Test.java
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/MigrateMarkersSearchResultTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/UpdateStaticAnalysisPackageTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java
  rewrite-java/src/main/java/org/openrewrite/java/Assertions.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java
  rewrite-maven/src/main/java/org/openrewrite/maven/Assertions.java
  rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
  rewrite-test/src/main/java/org/openrewrite/test/SourceSpec.java
  rewrite-test/src/main/java/org/openrewrite/test/TypeValidation.java
Labels: enhancement

#3565 Enable variable declaration type attribution checking
  rewrite-java-test/src/test/java/org/openrewrite/java/VariableNameUtilsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/RenameJavaDocParamNameVisitorTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeFieldName.java
  rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java
  rewrite-test/src/main/java/org/openrewrite/test/TypeValidation.java
Labels: enhancement
