Repository openrewrite/rewrite, pull requests merged in 2024-08, with the labels that each got.

#4370 Remove temporary JavaTemplate files
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
Labels: enhancement

#4379 Only add a Gradle wrapper if there is a Gradle project
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
Labels: enhancement

#4377 Added test property for FAIL_ON_UNKNOWN_PROPERTIES configuration
  rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
  rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java
  rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java
Labels: enhancement

#4380 Ignore module-info.java files for now
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Labels: bug

#4387 Retain dependencyManagement entries with exclusions
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveRedundantDependencyVersionsTest.java
Labels: bug

#4392 fix: CommentOutProperty to work with single keys
  rewrite-yaml/src/main/java/org/openrewrite/yaml/CommentOutProperty.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/CommentOutPropertyTest.java
Labels: bug, good first issue

#4393 fix: Include port in GitRemote origin
  rewrite-core/src/main/java/org/openrewrite/GitRemote.java
  rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Labels: bug

#4394 Add GradleDependency trait
  rewrite-gradle/src/main/java/org/openrewrite/gradle/trait/GradleDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/trait/GradleTraitMatcher.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/trait/package-info.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/trait/GradleDependencyTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/trait/Traits.java
Labels: enhancement

#4399 fix: Allow deserialization of GitProvenance
  rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java
  rewrite-core/src/test/java/org/openrewrite/marker/GitProvenanceTest.java
Labels: bug

#4383 Fix issue in ChangeStaticFieldToMethod when used in (implied) array
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeStaticFieldToMethodTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/marker/JavaSourceSetTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeStaticFieldToMethod.java
Labels: bug

#4372 Isolate JavaTemplate issue with generic type parameters
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
  rewrite-java/src/main/java/org/openrewrite/java/TreeVisitingPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
Labels: bug

#4408 Parse packages.config as XML for C#
  rewrite-xml/src/main/java/org/openrewrite/xml/XmlParser.java
Labels: enhancement, parser-xml, parser-c#

#4421 Restore newArtifactId property in ChangePluginGroupIdAndArtifactId
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactId.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactIdTest.java
Labels: bug

#4406 `NoMissingTypes` does not work if the missing type is a return value of a method and the method has a parameter
  rewrite-java-tck/src/main/java/org/openrewrite/java/JavaParserTypeMappingTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/FindMissingTypesTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: bug

#4425 refactor: Simplify lambda blocks to expressions
  rewrite-java-test/src/test/java/org/openrewrite/RepeatTest.java
  rewrite-java/src/main/java/org/openrewrite/java/search/HasMinimumJavaVersion.java
  rewrite-java/src/test/java/org/openrewrite/java/trait/VariableAccessTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemovePropertyTest.java
  rewrite-test/src/test/java/org/openrewrite/RenameFileTest.java
Labels: enhancement

#4426 refactor: Remove unused imports
  rewrite-core/src/main/java/org/openrewrite/PathUtils.java
  rewrite-core/src/main/java/org/openrewrite/internal/lang/NonNullApi.java
  rewrite-core/src/main/java/org/openrewrite/internal/lang/NullUtils.java
  rewrite-core/src/main/java/org/openrewrite/internal/lang/Nullable.java
  rewrite-core/src/test/java/org/openrewrite/PathUtilsTest.java
  rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java
  rewrite-core/src/test/java/org/openrewrite/table/SourceFileResultsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/RepeatTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTypeTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/search/HasMinimumJavaVersionTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/search/IsOrIsNotLikelyTestTest.java
  rewrite-java/src/main/java/org/openrewrite/java/format/EmptyNewlineAtEndOfFile.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginConfiguration.java
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveManagedDependency.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/trait/NamespacedTest.java
Labels: enhancement

#4430 Use correct length for GString substrings
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Labels: bug

#4429 Support multiple protocols and ports for a single `GitRemote` server and build URIs
  rewrite-core/src/main/java/org/openrewrite/GitRemote.java
  rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
  rewrite-core/src/test/java/org/openrewrite/marker/GitProvenanceTest.java
Labels: enhancement

#4431 Groovy issues with Strings in parentheses
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/LiteralTest.java
Labels: bug, parser-groovy

#4427 Fixes for type attribution and `TypeUtils#isAssignableTo()`
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeMapping.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeSignatureBuilder.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeSignatureBuilder.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeMapping.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeSignatureBuilder.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeSignatureBuilder.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: bug, enhancement

#4433 fix: do not replace jgit in clone url (regex issue)
  rewrite-core/src/main/java/org/openrewrite/GitRemote.java
  rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Labels: bug

#3854 Updated detection of generic parameters in GroovyParserVisitor.
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MapEntryTest.java
Labels: bug, parser-groovy

#4435 fix: No protocol in origin
  rewrite-core/src/main/java/org/openrewrite/GitRemote.java
  rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Labels: bug

#4436 Add method to find a `GitRemote.RemoteServer` registered to the `GitRemote.Parser`
  rewrite-core/src/main/java/org/openrewrite/GitRemote.java
  rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Labels: enhancement

#4434 Do not merge in parent dependency where child overrides the version or scope
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: bug

#4442 Only extract annotations with template comment
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/AnnotationTemplateGenerator.java
  rewrite-java/src/test/java/org/openrewrite/java/ReplaceAnnotationTest.java
Labels: bug

#4445 Custom `distributionUrl` in gradle properties should be upgraded in place
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/util/GradleWrapper.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
  rewrite-gradle/src/test/resources/gradle-8.10-bin.zip
Labels: enhancement

#4458 `ChangeType` should fully qualify type usage in the case of conflicting imports
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Labels: bug
