Repository openrewrite/rewrite, pull requests merged in 2024-07, with the labels that each got.

#4284 Fix StackOverflowError in case of circular import deps
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: bug

#4297 MergeYaml should avoid adding query with no result as key at end of file
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Labels: bug

#4292 ChangeType leads to botched imports for nested fields
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Labels: bug

#4289 `AddParentPom` recipe
  rewrite-maven/src/main/java/org/openrewrite/maven/AddParentPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddParentPomTest.java
Labels: recipe

#4285 Handle MavenMetadata parser result NPE as reported by community member
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenMetadata.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenMetadataTest.java
Labels: bug

#4287 Add XPath support for namespace-uri() condition and attribute elements
  rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java
  rewrite-xml/src/main/java/org/openrewrite/xml/tree/Namespaced.java
  rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java
  rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
Labels: enhancement

#4296 RemoveObjectsIsNull fails on negated expressions fixed
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveObjectsIsNullTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveObjectsIsNull.java
Labels: bug

#4302 Switch to a single timeout for MavenSettings and MavenRepositoryMirror
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenSettings.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepository.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepositoryMirror.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenSettingsTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/tree/MavenRepositoryMirrorTest.java
Labels: bug

#4307 Fix method name collisions with UseStaticImport
  rewrite-java-test/src/test/java/org/openrewrite/java/UseStaticImportTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/search/MaybeUsesImportTest.java
  rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java
Labels: bug

#4300 Resolved stackoverflow exception for circular dependencies.
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
Labels: bug

#4305 XPath condition enhancements - multiple conditions and and/or operators
  rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java
  rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
Labels: enhancement

#4308 Fix/connection timeout in test
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Labels: enhancement

#4311 Added Profile dependency migration
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactIdTest.java
Labels: enhancement

#4309 `Trait` interface and `VariableAccess`/`MethodAccess` implementation
  rewrite-core/src/main/java/org/openrewrite/trait/SimpleTraitMatcher.java
  rewrite-core/src/main/java/org/openrewrite/trait/Trait.java
  rewrite-core/src/main/java/org/openrewrite/trait/TraitMatcher.java
  rewrite-core/src/main/java/org/openrewrite/trait/VisitFunction.java
  rewrite-core/src/main/java/org/openrewrite/trait/VisitFunction2.java
  rewrite-core/src/main/java/org/openrewrite/trait/package-info.java
  rewrite-java/src/main/java/org/openrewrite/java/trait/MethodAccess.java
  rewrite-java/src/main/java/org/openrewrite/java/trait/VariableAccess.java
  rewrite-java/src/main/java/org/openrewrite/java/trait/internal/MaybeParenthesesPair.java
  rewrite-java/src/main/java/org/openrewrite/java/trait/internal/package-info.java
  rewrite-java/src/main/java/org/openrewrite/java/trait/package-info.java
  rewrite-java/src/test/java/org/openrewrite/java/trait/MethodAccessTest.java
  rewrite-java/src/test/java/org/openrewrite/java/trait/VariableAccessTest.java
Labels: enhancement

#4317 feat: Change maven managed dependency classifier
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyClassifier.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyClassifierTest.java
Labels: enhancement

#4312 Migrate add Develocity recipes to handle the new develocity configurations
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePlugin.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePluginTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDevelocityMavenExtension.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddDevelocityMavenExtensionTest.java
Labels: enhancement, recipe

#4320 Add Gradle Enterprise to Develocity 3.17+ migration recipe for Gradle
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/MigrateGradleEnterpriseToDevelocity.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/MigrateGradleEnterpriseToDevelocityTest.java
Labels: enhancement, recipe

#4327 Gradle UpgradeDependencyVersion visitor should override isAcceptable
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Labels: bug

#3606 Add XSLT transformation recipe
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginConfiguration.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangePluginConfigurationTest.java
  rewrite-maven/src/test/resources/changePlugin.xslt
  rewrite-xml/src/main/java/org/openrewrite/xml/XsltTransformation.java
  rewrite-xml/src/main/java/org/openrewrite/xml/XsltTransformationVisitor.java
  rewrite-xml/src/test/java/org/openrewrite/xml/XsltTransformationTest.java
  rewrite-xml/src/test/resources/org/openrewrite/xml/XsltTransformationTest.xslt
Labels: recipe

#4326 feat: add shell executor interface for running shell commands during recipe execution
  rewrite-core/src/main/java/org/openrewrite/shell/exec/ShellExecutor.java
Labels: enhancement

#4335 Fixed maven multi module property version problem
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: bug

#4346 `EmptyNewlineAtEndOfFile` should retain non-whitespace characters
  .github/workflows/receive-pr.yml
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/MigrateGradleEnterpriseToDevelocityTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/UseStaticImportTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/format/EmptyNewlineAtEndOfFileTest.java
  rewrite-java/src/main/java/org/openrewrite/java/format/EmptyNewlineAtEndOfFile.java
Labels: bug, parser-groovy

#3929 Fixed ChangeType for stackoverflow
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Labels: bug, parser-kotlin

#4349 Do not wrap single active recipe & remove `activateAll()`
  rewrite-core/src/main/java/org/openrewrite/config/Environment.java
  rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java
  rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java
  rewrite-core/src/test/java/org/openrewrite/table/SourceFileResultsTest.java
  rewrite-core/src/test/resources/META-INF/rewrite/test-sample-a.yml
  rewrite-core/src/test/resources/META-INF/rewrite/test-sample-b.yml
  rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceStringLiteralWithConstantTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/search/HasJavaVersionTest.java
  rewrite-java-test/src/test/java/org/openrewrite/text/FindAndReplaceJavaTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RenamePropertyKeyTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/search/FindPluginTest.java
  rewrite-test/src/test/java/org/openrewrite/config/EnvironmentTest.java
  rewrite-test/src/test/resources/META-INF/rewrite/rewrite.yml
Labels: enhancement

#4342 Fix AddOrUpdateAnnotationAttribute for values of type Class
  rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
Labels: bug, enhancement

#4339 Fix UpgradeDependencyVersion handling of exactVersion with versionPattern
  rewrite-core/src/main/java/org/openrewrite/semver/ExactVersion.java
  rewrite-core/src/main/java/org/openrewrite/semver/ExactVersionWithPattern.java
  rewrite-core/src/main/java/org/openrewrite/semver/Semver.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
Labels: bug, enhancement

#4356 fix: Dont generate the same file multiple times & fix CreateTextFile
  rewrite-core/src/main/java/org/openrewrite/internal/InMemoryLargeSourceSet.java
  rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeRunCycle.java
  rewrite-core/src/main/java/org/openrewrite/text/CreateTextFile.java
  rewrite-test/src/test/java/org/openrewrite/text/CreateTextFileTest.java
Labels: bug

#4363 Add recipe for adding/replacing a Maven runtime config
  rewrite-maven/src/main/java/org/openrewrite/maven/AddRuntimeConfig.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddRuntimeConfigTest.java
Labels: recipe

#4365 Merge yaml test for inline comments retention
  rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Labels: bug
