Repository openrewrite/rewrite, pull requests merged in 2024-02, with the labels that each got.

#3963 `JavaTemplate` matching on parameterized types
  rewrite-groovy/src/test/java/org/openrewrite/groovy/JavaTemplateMatchTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest8Test.java
  rewrite-java/build.gradle.kts
  rewrite-java/src/main/antlr/TemplateParameterLexer.g4
  rewrite-java/src/main/antlr/TemplateParameterLexer.tokens
  rewrite-java/src/main/antlr/TemplateParameterParser.g4
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplateSemanticallyEqual.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/AnnotationSignatureLexer.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/AnnotationSignatureParser.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/AnnotationSignatureParserBaseListener.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/AnnotationSignatureParserBaseVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/AnnotationSignatureParserListener.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/AnnotationSignatureParserVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/MethodSignatureLexer.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/MethodSignatureParser.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/MethodSignatureParserBaseListener.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/MethodSignatureParserBaseVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/MethodSignatureParserListener.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/MethodSignatureParserVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterLexer.interp
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterLexer.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterLexer.tokens
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParser.interp
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParser.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParser.tokens
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserBaseListener.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserBaseVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserListener.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/TypeParameter.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
  rewrite-java/src/test/java/org/openrewrite/java/internal/template/TypeParameterTest.java
Labels: enhancement

#3965 Make ChangePropertyValue regex allow for multiple replacements of same regex pattern in single value
  rewrite-properties/src/main/java/org/openrewrite/properties/ChangePropertyValue.java
  rewrite-properties/src/test/java/org/openrewrite/properties/ChangePropertyValueTest.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyValue.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/ChangePropertyValueTest.java
Labels: enhancement

#3967 fix: profile specific plugins were not matched
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactIdTest.java
Labels: enhancement

#3962 Also update Maven managed dependency by default in `ChangeDependencyGroupIdAndArtifactId`
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/utilities/RetainVersions.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
Labels: enhancement

#3968 Changes packaging only if it matches provided packaging
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangePackaging.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangePackagingTest.java
Labels: enhancement

#3784 Use `Tree.randomId()` to construct LST elements, not `UUID.randomUUID()`
  rewrite-java/src/main/java/org/openrewrite/java/recipes/UseTreeRandomId.java
  rewrite-java/src/test/java/org/openrewrite/java/recipes/UseTreeRandomIdTest.java
Labels: recipe

#3973 Limit `RecipeEqualsAndHashCodeCallSuper` to `Recipe` and `callSuper`
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/RecipeEqualsAndHashCodeCallSuperTest.java
  rewrite-java/src/main/java/org/openrewrite/java/recipes/RecipeEqualsAndHashCodeCallSuper.java
Labels: bug

#3971 Submit dependency graph to GitHub after publish
  .github/workflows/dependency-submission.yml
Labels: documentation, github_actions

#3983 Simplifying UpdateJavaCompatibility recipe's options for addingIfMiss…
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateJavaCompatibility.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateJavaCompatibilityTest.java
Labels: enhancement

#3985 Allow non-period terminated Recipe descriptions
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
  rewrite-test/src/test/java/org/openrewrite/test/internal/RewriteTestTest.java
Labels: documentation

#3989 Assorted UpdateMavenWrapper fixes
  rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenWrapper.java
  rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenWrapper.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenWrapperTest.java
Labels: bug

#3990 Add RewriteTestClassesShouldNotBePublic recipe for reviews
  rewrite-java/src/main/java/org/openrewrite/java/recipes/RewriteTestClassesShouldNotBePublic.java
  rewrite-java/src/test/java/org/openrewrite/java/recipes/RewriteTestClassesShouldNotBePublicTest.java
Labels: recipe

#3944 Fully remove part provider and last remaining references
  rewrite-java/src/main/java/org/openrewrite/java/PartProvider.java
Labels: enhancement

#3988 Add test for updating parent gradle.properties when dependency is in …
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Labels: bug, test provided

#3999 Add `LargeSourceSet#beforeCycle(boolean)`
  rewrite-core/src/main/java/org/openrewrite/LargeSourceSet.java
  rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
Labels: enhancement

#4013 Fixed regex in XPathMatcher to support dots
  rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java
  rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
Labels: bug

#4009 Enhance autoformat logic for Groovy files
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/format/AutoFormat.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/format/AutoFormatVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/format/MinimumViableSpacingVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/service/GroovyAutoFormatService.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/G.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/format/AutoFormatVisitorTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/format/NormalizeLineBreaksTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/format/NormalizeTabsOrSpacesTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ConstructorTest.java
Labels: bug, enhancement, parser-groovy

#4002 ChangeParentPom now allows changing groupId/artifactId in the case wh…
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
Labels: enhancement

#4022 Only process markers when using type in AddDependency
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
Labels: enhancement

#4034 Make `MethodMatcher` more lightweight
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeMethodNameTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodName.java
  rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
  rewrite-java/src/main/java/org/openrewrite/java/TypeMatcher.java
Labels: performance

#4036 Fix documentation example for maven.AddPlugin
  rewrite-maven/src/main/java/org/openrewrite/maven/AddPlugin.java
Labels: bug, documentation

#4037 Only report unrecovered repositoryAccessFailed
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
Labels: enhancement

#4039 Save identified type on cache for future lookups on `ChangeType`.
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Labels: enhancement

#4040 Fixing swallowed compilation errors due to package name / path mismatch when using JavaParser's `dependsOn`.
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Labels: bug

#4046 `JavaParser` should favor public classes when naming source inputs
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Labels: bug

#4047 Add `AddNullMethodArgument` recipe
  rewrite-java-test/src/test/java/org/openrewrite/java/AddNullMethodArgumentTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddNullMethodArgument.java
Labels: recipe

#4049 Make @Issue repeatable
  rewrite-test/src/main/java/org/openrewrite/Issue.java
Labels: documentation, enhancement

#4053 Add recipe `AddLiteralMethodArgument`
  rewrite-java-test/src/test/java/org/openrewrite/java/AddLiteralMethodArgumentTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddLiteralMethodArgument.java
Labels: recipe

#4060 Previsit method invocations for `gradle.ChangePlugin`
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyVersionSelector.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddBuildPlugin.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePlugin.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddSettingsPlugin.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/ChangePlugin.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/ChangePluginTest.java
Labels: bug
