Repository openrewrite/rewrite, pull requests merged in 2024-10, with the labels that each got.

#4530 Make Plugin.getGroupId() NonNull
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Plugin.java
Labels: bug

#4554 Remove maven properties should remove comment
  rewrite-maven/src/main/java/org/openrewrite/maven/AddProfile.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddRepository.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyClassifier.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyScope.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ManageDependencies.java
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveManagedDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/RemovePlugin.java
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveProperty.java
  rewrite-maven/src/main/java/org/openrewrite/maven/cleanup/DependencyManagementDependencyRequiresVersion.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddProfileTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemovePropertyTest.java
  rewrite-xml/src/main/java/org/openrewrite/xml/RemoveContentVisitor.java
  rewrite-xml/src/main/java/org/openrewrite/xml/RemoveEmptyXmlTags.java
  rewrite-xml/src/main/java/org/openrewrite/xml/RemoveXmlTag.java
  rewrite-xml/src/test/java/org/openrewrite/xml/RemoveContentTest.java
Labels: enhancement

#4555 Use reflection to invoke getCommentTree to support Java 21 & 23
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
Labels: bug, enhancement

#4557 Add recipe to remove mutable static fields from Recipes
  rewrite-java/src/main/java/org/openrewrite/java/recipes/NoMutableStaticFieldsInRecipes.java
  rewrite-java/src/test/java/org/openrewrite/java/recipes/NoMutableStaticFieldsInRecipesTest.java
Labels: recipe

#4515 feat: added check for duplicated dependency
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactIdTest.java
Labels: bug, enhancement

#4446 Added arrays to AddOrUpdateAnnotationAttribute
  rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
Labels: enhancement

#4577 Detect whitespace before import semicolon
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ImportTest.java
Labels: bug, parser-java

#4580 Link to FAQ on missing types in tests
  rewrite-java/src/main/java/org/openrewrite/java/Assertions.java
Labels: documentation

#4588 Fix missing junit-platform-launcher version
  rewrite-java-8/build.gradle.kts
  rewrite-java/build.gradle.kts
  rewrite-test/build.gradle.kts
Labels: bug, enhancement

#4591 Actually use TLS in (some) Maven tests and shove a few minutes from their execution
  rewrite-maven/build.gradle.kts
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeParentVersionTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Labels: enhancement

#4594 ChangePropertyValue in list yaml entries
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyValue.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/ChangePropertyValueTest.java
Labels: enhancement

#4529 Make ParentPomInsight recursive
  rewrite-core/src/main/java/org/openrewrite/semver/Semver.java
  rewrite-maven/src/main/java/org/openrewrite/maven/search/ParentPomInsight.java
  rewrite-maven/src/test/java/org/openrewrite/maven/search/ParentPomInsightTest.java
Labels: recipe

#4590 Apply add dependency correctly, taking aggregating poms into account
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenResolutionResult.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/RawPomTest.java
Labels: enhancement

#4616 Fix parsing of HCL comments using //
  rewrite-hcl/build.gradle.kts
  rewrite-hcl/src/main/java/org/openrewrite/hcl/Assertions.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/HclParserVisitor.java
  rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclCommentTest.java
  rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclStringTest.java
Labels: bug, parser-hcl

#4592 UpgradeParentVersion: option to only upgrade external parents
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeParentVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Parent.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddRepositoryTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenDependencyFailuresTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeParentVersionTest.java
Labels: enhancement

#4617 Simplify constant ternary expressions too
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitor.java
Labels: enhancement

#4618 Backport DocCommentTree reflection to ReloadableJava17ParserVisitor
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
Labels: bug, enhancement

#4609 Fix failing test and infinity loop in MavenPomDownloader
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Labels: bug

#4610 Add Recipe that allows for the removal/negation of gitignore rules.
  rewrite-core/src/main/java/org/openrewrite/ExcludeFileFromGitignore.java
  rewrite-core/src/test/java/org/openrewrite/ExcludeFileFromGitignoreTest.java
Labels: recipe

#4625 Allowing for trailing dollars and percent signs in String literals
  rewrite-hcl/src/main/antlr/HCLLexer.g4
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/HCLLexer.interp
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/HCLLexer.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/HCLParser.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/HCLParserBaseListener.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/HCLParserBaseVisitor.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/HCLParserListener.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/HCLParserVisitor.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/JsonPathLexer.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/JsonPathParser.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/JsonPathParserBaseListener.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/JsonPathParserBaseVisitor.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/JsonPathParserListener.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar/JsonPathParserVisitor.java
  rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclStringTest.java
Labels: bug, parser-hcl

#4624 Comments cannot be parsed properly
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
Labels: bug, parser-java

#4627 Check that we have downloaded the file successfully
  rewrite-core/build.gradle.kts
  rewrite-core/src/main/java/org/openrewrite/remote/RemoteArchive.java
  rewrite-core/src/main/java/org/openrewrite/remote/RemoteFile.java
  rewrite-core/src/test/java/org/openrewrite/remote/RemoteArchiveTest.java
  rewrite-core/src/test/java/org/openrewrite/remote/RemoteFileTest.java
  rewrite-test/src/main/java/org/openrewrite/test/MockHttpSender.java
Labels: bug

#4630 Prevent NPE on older LSTs not yet containing ResolvedPom.subprojects
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenResolutionResult.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
Labels: bug

#4631 Fixed negation of nested files and directories if excluded by another rule
  rewrite-core/src/main/java/org/openrewrite/ExcludeFileFromGitignore.java
  rewrite-core/src/test/java/org/openrewrite/ExcludeFileFromGitignoreTest.java
Labels: bug, enhancement

#4620 `JavaParser` with `classpathFromResources` fails on Java 21
  rewrite-java-21/src/test/java/org/openrewrite/java/.editorconfig
  rewrite-java-21/src/test/java/org/openrewrite/java/Java21ParserTest.java
  rewrite-java-21/src/test/resources/META-INF/rewrite/classpath/jackson-annotations-2.17.1.jar
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Labels: bug, parser-java, java 21+
