Repository openrewrite/rewrite, pull requests merged in 2024-04, with the labels that each got.

#4074 `MavenVisitor` should not return incorrect `ResolutionResult` for multi module maven projects
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/test/java/org/openrewrite/maven/search/FindDependencyTest.java
Labels: bug

#4124 fix invalid jarPattern in JavaParser
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Labels: bug

#4133 Test case for XPath Matcher matches too many tags when using relative Paths and conditions
  rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java
  rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
Labels: bug

#4146 Adds support for merging plugins executions
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Plugin.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/tree/ResolvedPomTest.java
Labels: enhancement, parser-maven

#4130 Add providedCompile to the DependencyHandlerSpec for ChangeDependency gradle
  rewrite-gradle/src/main/groovy/RewriteGradleProject.groovy
  rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyTest.java
Labels: enhancement

#4150 Restore adding missing prefix in MergeYaml
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Labels: bug

#4155 fix: use aroundMethod for anonymous inner class in blankLines
  rewrite-java-test/src/test/java/org/openrewrite/java/format/BlankLinesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/format/BlankLinesVisitor.java
Labels: bug

#4156 Modify default behaviour of MavenVisitor::isPluginTag() to search everywhere, not just build
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactIdTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradePluginVersionTest.java
Labels: enhancement

#4162 Allow non-eager application of Gradle plugins
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddBuildPlugin.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePlugin.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddSettingsPlugin.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddBuildPluginTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddSettingsPluginTest.java
Labels: enhancement

#4159 Cache mirrors in `MavenPomDownloader`
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
Labels: performance
