Repository openrewrite/rewrite, pull requests merged in 2024-11, with the labels that each got.

#4587 Add `TypeReference` trait to identify Java type references in XML
  rewrite-core/src/main/java/org/openrewrite/SourceFileWithTypeReferences.java
  rewrite-core/src/main/java/org/openrewrite/TypeReferenceProvider.java
  rewrite-core/src/main/java/org/openrewrite/trait/TypeReference.java
  rewrite-java-test/src/test/java/org/openrewrite/java/search/FindTypesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
  rewrite-java/src/main/java/org/openrewrite/java/TypeMatcher.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindTypes.java
  rewrite-java/src/main/java/org/openrewrite/java/search/UsesType.java
  rewrite-xml/src/main/java/org/openrewrite/xml/trait/SpringTypeReference.java
  rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java
  rewrite-xml/src/main/resources/META-INF/services/org.openrewrite.trait.TypeReference$Provider
  rewrite-xml/src/test/java/org/openrewrite/xml/XmlParserTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/trait/SpringTypeReferenceTest.java
Labels: enhancement

#4602 Support Lombok
  IDE.properties.tmp
  rewrite-java-17/build.gradle.kts
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java
  rewrite-java-lombok/build.gradle.kts
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/AllArgsConstructorHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/CleanupNoOpHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/ExtensionMethodHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/GetterHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/HelperHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/JacksonizedHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/LockedNoOpHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/LockedReadNoOpHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/LockedWriteNoOpHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/NoArgsConstructorHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/NonNullNoOpHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/OpenRewriteConfigurationKeysLoader.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/RequiredArgsConstructorHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/SetterHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/SneakyThrowsNoOpHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/SynchronizedNoOpHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/package-info.java
  rewrite-java-lombok/src/main/resources/META-INF/services/lombok.core.configuration.ConfigurationKeysLoader
  rewrite-java-lombok/src/main/resources/META-INF/services/lombok.javac.JavacAnnotationHandler
  rewrite-java-tck/src/main/java/org/openrewrite/java/JavaParserTypeMappingTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/LombokTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/VariableDeclarationsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/format/SpacesTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/search/SemanticallyEqualTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaUnrestrictedClassLoader.java
  rewrite-java/src/test/java/org/openrewrite/java/OpenRewriteArchitectureTest.java
  settings.gradle.kts
Labels: enhancement, parser-java

#4666 Account for a second common resource filtering pattern
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveUnusedProperties.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveUnusedPropertiesTest.java
Labels: bug

#4648 Update `ChangeType` and `ChangePackage` to work with `SourceFileWithReference`
  rewrite-core/src/main/java/org/openrewrite/SourceFileWithReferences.java
  rewrite-core/src/main/java/org/openrewrite/SourceFileWithTypeReferences.java
  rewrite-core/src/main/java/org/openrewrite/TypeReferenceProvider.java
  rewrite-core/src/main/java/org/openrewrite/trait/Reference.java
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
  rewrite-java/src/main/java/org/openrewrite/java/PackageMatcher.java
  rewrite-java/src/main/java/org/openrewrite/java/TypeMatcher.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindTypes.java
  rewrite-java/src/main/java/org/openrewrite/java/search/UsesType.java
  rewrite-xml/src/main/java/org/openrewrite/xml/trait/SpringReference.java
  rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java
  rewrite-xml/src/main/resources/META-INF/services/org.openrewrite.trait.Reference$Provider
  rewrite-xml/src/main/resources/META-INF/services/org.openrewrite.trait.TypeReference$Provider
  rewrite-xml/src/test/java/org/openrewrite/xml/XmlParserTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/trait/SpringReferenceTest.java
Labels: enhancement, recipe

#4663 Update model for interfaces extending interfaces
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: bug, parser-java

#4672 Fix bug using `AddOrUpdateAnnotationAttribute` on annotation with empty brackets
  rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
Labels: bug

#4670 ChangeType does not work on J.ClassDeclaration
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Labels: bug

#4677 Remove redundant space for DeleteMethodArgument when argumentIndex=0
  rewrite-gradle/src/test/java/org/openrewrite/gradle/search/FindPluginsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/DeleteMethodArgumentTest.java
  rewrite-java/src/main/java/org/openrewrite/java/DeleteMethodArgument.java
Labels: bug, enhancement

#4667 Append items to annotation attribute array
  rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
  rewrite-java/src/main/java/org/openrewrite/java/recipes/MissingOptionExample.java
Labels: enhancement

#4689 Call `isTrue` on `Reference` asserts in `XmlParserTest`
  rewrite-xml/src/test/java/org/openrewrite/xml/XmlParserTest.java
Labels: bug

#4691 Fix NPE in `SpringReference`
  rewrite-xml/src/main/java/org/openrewrite/xml/trait/SpringReference.java
Labels: bug

#4688 Make `FindMissingTypes` stricter for method invocations
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: enhancement

#4693 Find Refaster style recipes as well
  rewrite-core/src/main/java/org/openrewrite/table/RewriteRecipeSource.java
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/FindRecipesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/recipes/FindRecipes.java
Labels: enhancement

#4695 Find Yaml recipes as well
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/FindRecipesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/recipes/FindRecipes.java
Labels: recipe

#4671 When merging yaml files comments on the last element of existing block are placed at the wrong line
  rewrite-core/src/main/java/org/openrewrite/Cursor.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYamlVisitor.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/tree/Yaml.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Labels: bug, recipe

#4709 Add missing semicolon to JavaTemplate stub when replacing method arguments
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
Labels: bug

#4712 Restrict usage of `RecipeList` methods from `ScanningRecipe`
  rewrite-core/src/main/java/org/openrewrite/ScanningRecipe.java
  rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
Labels: enhancement

#4694 Add `AddAnnotationProcessor` recipe
  rewrite-maven/src/main/java/org/openrewrite/maven/AddAnnotationProcessor.java
  rewrite-maven/src/main/java/org/openrewrite/maven/trait/MavenPlugin.java
  rewrite-maven/src/main/java/org/openrewrite/maven/trait/MavenTraitMatcher.java
  rewrite-maven/src/main/java/org/openrewrite/maven/trait/Traits.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddAnnotationProcessorTest.java
Labels: enhancement, recipe

#4719 Add a new recipe to add comments to a Java method
  rewrite-java/src/main/java/org/openrewrite/java/AddCommentToMethod.java
  rewrite-java/src/test/java/org/openrewrite/java/AddCommentToMethodTest.java
Labels: recipe

#4724 Exclude omitted dependencies as well through a second cycle
  rewrite-maven/src/main/java/org/openrewrite/maven/ExcludeDependency.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ExcludeDependencyTest.java
Labels: enhancement

#4727 Allow orgs with leading numbers in name in GitRemote
  rewrite-core/src/main/java/org/openrewrite/GitRemote.java
  rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Labels: bug

#4651 Update `GitRemote#normalize` to support organizations prefixed with a number
  rewrite-core/src/main/java/org/openrewrite/GitRemote.java
  rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Labels: bug

#4729 Restore ListUtils map methods that accept UnaryOperator
  rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java
Labels: bug

#4692 Add version tag for managed dependency with property
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
Labels: bug
