Repository openrewrite/rewrite, pull requests merged in 2024-12, with the labels that each got.

#4735 Resove dependencies bom with properties on `ChangeParentPom`
  rewrite-core/src/main/java/org/openrewrite/internal/PropertyPlaceholderHelper.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
Labels: bug

#4725 Add `NamingService` with Java implementation
  rewrite-core/src/main/java/org/openrewrite/internal/NamingService.java
  rewrite-java/src/main/java/org/openrewrite/java/service/JavaNamingService.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaSourceFile.java
  rewrite-java/src/test/java/org/openrewrite/java/service/JavaNamingServiceTest.java
Labels: enhancement

#4742 Fix Gradle/Groovy parser issue related to Java class references
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Labels: bug

#4744 Take `J.Case` into account in JavaTemplate
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
Labels: bug

#4749 Always add closing semicolon for `J.Case` in JavaTemplate
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
Labels: bug

#4747 Fix AddImport match variable's name
  rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
Labels: bug

#4750 Update get classpath by artifact name to support bazel
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Labels: enhancement

#4733 Add RegExp support to ChangeTagValue recipe
  rewrite-maven/src/main/java/org/openrewrite/maven/IncrementProjectVersion.java
  rewrite-xml/src/main/java/org/openrewrite/xml/ChangeTagValue.java
  rewrite-xml/src/test/java/org/openrewrite/xml/ChangeTagValueTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/ChangeTagValueVisitorTest.java
Labels: enhancement

#4753 Adding master password decrypting
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenSecuritySettings.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenSettings.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenSecuritySettingsTest.java
Labels: enhancement

#4754 `RemoveMethodInvocationsVisitor` can remove static method
  rewrite-java/src/main/java/org/openrewrite/java/RemoveMethodInvocationsVisitor.java
  rewrite-java/src/test/java/org/openrewrite/java/RemoveMethodInvocationsVisitorTest.java
Labels: bug, recipe

#4492 Remove redundant versions for Gradle
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyClassifier.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveRedundantDependencyVersions.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveRedundantDependencyVersionsTest.java
Labels: recipe

#4758 Performance improvements of `Find` recipe
  rewrite-core/src/main/java/org/openrewrite/text/Find.java
  rewrite-core/src/test/java/org/openrewrite/text/FindTest.java
Labels: enhancement

#4772 Groovy parser does not support multiple closure arguments without parentheses
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
Labels: bug, parser-groovy

#4774 Correct `J.FieldAccess#isFullyQualifiedClassReference()`
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: bug

#4778 Drop unused GraphvizResolutionEventListener & dependency
  rewrite-maven/build.gradle.kts
  rewrite-maven/dependency-viz.kt
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/VersionRequirement.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/GraphvizResolutionEventListener.java
Labels: enhancement, dependencies

#4738 Allow pom download failures
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/tree/ResolvedPomTest.java
Labels: bug, enhancement

#4787 Always add import for `Record` classes not from `java.lang` package, to avoid conflicts on Java 14+
  rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
Labels: bug, enhancement

#4786 Add `testRuntimeOnly` dependency on `junit-platform-launcher` with Gradle 8.+
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-8.yml
  rewrite-gradle/src/test/java/org/openrewrite/gradle/AddJUnitPlatformLauncherTest.java
  rewrite-test/build.gradle.kts
Labels: recipe

#4757 Fix groovy multivariable declaration
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/marker/MultiVariable.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AssignmentTest.java
Labels: bug

#4788 enhance UpgradeDependencyVersionTest
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Labels: test provided

#4798 fix[maven]: update plugin dependencies
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
Labels: enhancement

#4412 Handle erroneous nodes in open rewrite
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaVisitorTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeStaticFieldToMethod.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaIsoVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindCompileErrors.java
  rewrite-java/src/main/java/org/openrewrite/java/table/CompileErrors.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
  rewrite-java/src/test/java/org/openrewrite/java/search/FindCompileErrorsTest.java
Labels: enhancement

#4801 Make Groovy Parser correctly handle nested parenthesis
  rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AttributeTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/CastTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ListTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/LiteralTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MapEntryTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RangeTest.java
Labels: bug, parser-groovy

#4809 Add recipe to remove Gradle Enterprise and Develocity
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/RemoveDevelocityConfiguration.java
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle.yml
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/RemoveDevelocityTest.java
Labels: recipe

#4791 Allow file scheme in `RemoteArchive` to simplify testing
  rewrite-core/src/main/java/org/openrewrite/remote/RemoteArchive.java
  rewrite-core/src/test/java/org/openrewrite/remote/RemoteArchiveTest.java
  rewrite-core/src/test/java/org/openrewrite/remote/RemoteFileTest.java
  rewrite-core/src/test/resources/zipfile.zip
Labels: enhancement

#4807 Add fallback for determining parenthesis level for `BinaryExpression`
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Labels: bug

#4810 Add a `isClassAvailable` method to the ReflectionUtils
  rewrite-core/src/main/java/org/openrewrite/internal/ReflectionUtils.java
  rewrite-core/src/test/java/org/openrewrite/internal/ReflectionUtilsTest.java
Labels: enhancement

#4812 Correctly map generic return and parameter types in `JavaReflectionTypeMapping`
  rewrite-java-test/src/main/java/org/openrewrite/java/JavaTypeMappingTest.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/JavaReflectionTypeMapping.java
Labels: bug

#4814 Keep the names of generic type variables defined by methods.
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeMapping.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeMapping.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java
  rewrite-java-test/src/main/java/org/openrewrite/java/JavaTypeMappingTest.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/JavaReflectionTypeMapping.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Labels: enhancement

#4815 Fix Java reflection mapping of generic typed fields.
  rewrite-java-test/src/main/java/org/openrewrite/java/JavaTypeGoat.java
  rewrite-java-test/src/main/java/org/openrewrite/java/JavaTypeMappingTest.java
  rewrite-java-test/src/main/resources/JavaTypeGoat.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/JavaReflectionTypeMapping.java
Labels: bug

#4818 Revert parenthesis changes
  rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AttributeTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/CastTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ListTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/LiteralTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MapEntryTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RangeTest.java
Labels: bug

#4806 JavaTemplate bug when inserting `final var` into for-each
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
Labels: bug

#4793 Add Docker Image reference, to be used for gitlab, docker, etc
  rewrite-core/src/main/java/org/openrewrite/SourceFileWithReferences.java
  rewrite-core/src/main/java/org/openrewrite/text/Find.java
  rewrite-core/src/main/java/org/openrewrite/text/PlainText.java
  rewrite-core/src/main/java/org/openrewrite/text/PlainTextParser.java
  rewrite-core/src/main/java/org/openrewrite/trait/Reference.java
  rewrite-core/src/test/java/org/openrewrite/text/FindTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
  rewrite-java/src/main/java/org/openrewrite/java/search/FindTypes.java
  rewrite-java/src/main/java/org/openrewrite/java/search/UsesType.java
  rewrite-properties/src/main/java/org/openrewrite/properties/trait/PropertiesReference.java
  rewrite-properties/src/main/java/org/openrewrite/properties/tree/Properties.java
  rewrite-protobuf/src/main/java/org/openrewrite/protobuf/ProtoParser.java
  rewrite-xml/src/main/java/org/openrewrite/xml/trait/SpringXmlReference.java
  rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java
  rewrite-xml/src/test/java/org/openrewrite/xml/trait/SpringXmlReferenceTest.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/trait/YamlApplicationConfigReference.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/trait/YamlReference.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/tree/Yaml.java
  rewrite-yaml/src/main/resources/META-INF/services/org.openrewrite.trait.Reference$Provider
  rewrite-yaml/src/test/java/org/openrewrite/yaml/trait/YamlReferenceTest.java
Labels: enhancement

#4823 Add support for lombok @Builder.Default Annotation
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/BuilderDefaultNoOpHandler.java
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/BuilderHandler.java
  rewrite-java-lombok/src/main/resources/META-INF/services/lombok.javac.JavacAnnotationHandler
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/LombokTest.java
Labels: parser-java

#4819 Put parenthesis changes back
  rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AttributeTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/CastTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ForLoopTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ListTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/LiteralTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MapEntryTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodDeclarationTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RangeTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RealWorldGroovyTest.java
Labels: parser-groovy

#4824 Groovy parsers should be able to support `.class`
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AssignmentTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RealWorldGroovyTest.java
Labels: enhancement, parser-groovy

#4822 `AddAnnotationProcessor` should compare and update versions using a property
  rewrite-maven/src/main/java/org/openrewrite/maven/AddAnnotationProcessor.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddAnnotationProcessorTest.java
Labels: bug

#4769 Add lombok support for java-11
  rewrite-java-11/build.gradle.kts
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeMapping.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/LombokTest.java
Labels: parser-java
