Repository openrewrite/rewrite, pull requests merged in 2024-03, with the labels that each got.

#3475 Make `JavaTemplate` engine extensible
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/__M__.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/__P__.java
Labels: enhancement

#4066 Detect instanceof pattern variables in scope
  rewrite-java-test/src/test/java/org/openrewrite/java/VariableNameUtilsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/VariableNameUtils.java
Labels: bug

#4069 Update maven model when adding/changing properties to pom
  rewrite-maven/src/main/java/org/openrewrite/maven/AddProperty.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangePropertyValue.java
Labels: enhancement

#4082 Fix RenameVariable for variables referenced through type casts
  rewrite-java-test/src/test/java/org/openrewrite/java/RenameVariableTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
Labels: bug

#4085 Add table and version matcher to Maven FindProperties
  rewrite-maven/src/main/java/org/openrewrite/maven/search/FindProperties.java
  rewrite-maven/src/main/java/org/openrewrite/maven/table/MavenProperties.java
  rewrite-maven/src/test/java/org/openrewrite/maven/search/FindPropertiesTest.java
Labels: enhancement

#4081 ensuring connection timeouts get wrapped by MavenDownloadingException
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Labels: bug, enhancement

#4006 Add dependency now works with empty maven projects
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
Labels: enhancement

#4097 Warn about plain text specifics in AppendToTextFile.java
  rewrite-core/src/main/java/org/openrewrite/text/AppendToTextFile.java
Labels: documentation
