Repository openrewrite/rewrite, pull requests merged in 2024-06, with the labels that each got.

#4219 fix: Recognize bundle POM packaging type as jars when verifying recipe dependency downloads
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/tree/PomTest.java
Labels: bug

#4227 Strengthen override method determination for generic parameters
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Labels: bug

#4236 Add Property Resolution to RemoveRedundantDependencyVersions
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveRedundantDependencyVersionsTest.java
Labels: enhancement

#4242 Import get inserted at correct index with newline space
  rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
  rewrite-java/src/test/java/org/openrewrite/java/style/ImportLayoutStyleTest.java
Labels: bug

#4247 Add `AddPluginRepository` recipe
  rewrite-maven/src/main/java/org/openrewrite/maven/AddRepository.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddRepositoryTest.java
Labels: enhancement, recipe, test provided

#4245 Fix `Parameterized` is hidden by `withFullyQualifiedName`
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
  rewrite-java/src/test/java/org/openrewrite/java/internal/template/TypeParameterTest.java
Labels: bug

#4255 Add NlsRewrite hints to Refaster RecipeDescriptor fields
  rewrite-core/src/main/java/org/openrewrite/config/RecipeDescriptor.java
Labels: enhancement, question

#4260 Allow JavaTemplate to throw new Exception
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateSubstitutionsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
Labels: bug, enhancement

#4268 Gradle `ChangeDependencyClassifier` supports add and remove classifier
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyClassifier.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyClassifierTest.java
Labels: enhancement

#3951 Allow configuration of HTTP timeouts for maven repositories
  rewrite-core/src/main/java/org/openrewrite/ipc/http/HttpSender.java
  rewrite-core/src/main/java/org/openrewrite/ipc/http/HttpUrlConnectionSender.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenSettings.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepository.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepositoryMirror.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenSettingsTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/tree/MavenRepositoryMirrorTest.java
Labels: enhancement

#3925 Partial support for parsing XML namespaces
  rewrite-xml/src/main/java/org/openrewrite/xml/ChangeNamespaceValue.java
  rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java
  rewrite-xml/src/main/java/org/openrewrite/xml/search/FindNamespacePrefix.java
  rewrite-xml/src/main/java/org/openrewrite/xml/search/HasNamespaceUri.java
  rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java
  rewrite-xml/src/test/java/org/openrewrite/xml/ChangeNamespaceValueTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/CreateXmlFileTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/internal/XmlTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/search/FindNamespacePrefixTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/search/HasNamespaceUriTest.java
Labels: enhancement

#4276 Ignore method invocation arguments that are not string J.Literals
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Labels: bug

#4282 fix: fix bellwether decorated recipe ignoring causesAnotherCycle
  rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
Labels: bug

#4279 Add column names & descriptions for `MavenMetadataFailures`
  rewrite-maven/src/main/java/org/openrewrite/maven/table/MavenMetadataFailures.java
Labels: documentation

#4277 Add PlaintextOnly Option to FindAndReplace Recipe
  rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java
  rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java
  rewrite-core/src/test/java/org/openrewrite/RecipeRunTest.java
  rewrite-core/src/test/java/org/openrewrite/text/FindAndReplaceTest.java
  rewrite-java-test/src/test/java/org/openrewrite/text/FindAndReplaceJavaTest.java
Labels: enhancement

#4214 Improve UpgradeDependencyVersion to update dependency version whose value is defined via a property from the parent POM.
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
Labels: enhancement

#4290 Preserve multiple dependencyManagement with different types
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveDuplicateDependenciesTest.java
Labels: bug

#4291 Recreate static imports for identifiers in ChangeType
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Labels: bug
