Repository openrewrite/rewrite, pull requests merged in 2024-05, with the labels that each got.

#4163 Rename `J.InstanceOf.Padding#getExpr()` and `J.LambdaParameters.Padding#getParams()`
  rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveObjectsIsNull.java
  rewrite-java/src/main/java/org/openrewrite/java/format/OperatorWrap.java
  rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Labels: enhancement

#4168 Support NewClass in MethodMatcher and ChangeMethodName
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeMethodNameTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodName.java
  rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
Labels: enhancement

#4098 Add fileContentsUrl option for CreateYamlFile
  rewrite-yaml/src/main/java/org/openrewrite/yaml/CreateYamlFile.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/CreateYamlFileTest.java
Labels: enhancement

#4169 Suggest alternatives when active recipes are not found
  rewrite-core/src/main/java/org/openrewrite/config/Environment.java
  rewrite-test/src/test/java/org/openrewrite/config/EnvironmentTest.java
Labels: enhancement

#4174 ChangePackage fails to migrate annotation argument enum in package-info
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
Labels: bug

#4178 YAML: Support lists of lists
  rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Labels: bug, enhancement, parser-yaml

#4187 YAML: Support other cases of lists of lists
  rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Labels: parser-yaml

#4184 Don't modify package declaration of siblings in ChangeType
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
  rewrite-test/src/main/java/org/openrewrite/test/SourceSpec.java
Labels: bug, test provided

#4189 org.openrewrite.java.ChangePackage precise package match
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
Labels: bug

#4197 Fix bug adding import to a list of imports containing duplicate imports.
  rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
  rewrite-java/src/test/java/org/openrewrite/java/style/ImportLayoutStyleTest.java
Labels: bug

#4191 Added gradle recipe to remove enableFeaturePreview method
  rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveEnableFeaturePreview.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveEnableFeaturePreviewTest.java
Labels: recipe

#4201 ChangeMethodTargetToStatic should also change instance usage
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeMethodTargetToStaticTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodTargetToStatic.java
Labels: enhancement

#4186 bug: Handle NoClassDefFoundError when loading YAML recipes with missing recipe dependencies
  rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
  rewrite-core/src/test/java/org/openrewrite/config/YamlResourceLoaderTest.java
Labels: bug

#4148 RemoveRedundantDependencyVersions - adding `onlyIfManagedVersionIs` o…
  rewrite-core/src/test/java/org/openrewrite/config/YamlResourceLoaderTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveRedundantDependencyVersionsTest.java
Labels: enhancement

#4205 bug: yaml: DeleteProperty: do not remove unrelated empty sequences
  rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteProperty.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/DeletePropertyKeyTest.java
Labels: bug

#4208 Parse troublesome Yaml with new workaround in workaround for underying parser bug
  rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Labels: bug, parser-yaml

#4217 Add recipe to replace Annotation
  rewrite-java/src/main/java/org/openrewrite/java/ReplaceAnnotation.java
  rewrite-java/src/test/java/org/openrewrite/java/ReplaceAnnotationTest.java
Labels: recipe
