Repository openrewrite/rewrite, pull requests merged in 2024-09, with the labels that each got.

#4464 Retain default `ChangeType` behavior when dependency conflict cannot be determined
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Labels: bug

#4471 Add DoesNotUseType recipe for use in preconditions to reject source files
  rewrite-java/src/main/java/org/openrewrite/java/search/DoesNotUseType.java
  rewrite-java/src/test/java/org/openrewrite/java/search/DoesNotUseTypeTest.java
Labels: recipe

#4459 Add missing buildscript classpath configuration
  rewrite-gradle/build.gradle.kts
  rewrite-gradle/src/main/java/org/openrewrite/gradle/marker/GradleBuildscript.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/marker/GradleProject.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/marker/GradleSettings.java
Labels: enhancement

#4450 Static import is removed and leaves ambiguous reference behind
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
Labels: bug

#4376 Expand GradleDependency Trait to change dependencies in jvm-test-suite DSL & buildscript
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyArtifactId.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyClassifier.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyConfiguration.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyExtension.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyGroupId.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseMapNotation.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseStringNotation.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/trait/GradleDependency.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyArtifactIdTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyClassifierTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyConfigurationTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyExtensionTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyGroupIdTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/DependencyUseMapNotationTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/DependencyUseStringNotationTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveDependencyTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Labels: enhancement

#4479 `RemoveUnusedImports` should not remove imports for used nested classes
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
Labels: bug

#4482 `RemoveUnusedImports` should retain explicit import when there are conflicting classes in the same package
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
Labels: bug, test provided

#4484 Fallback to settings.xml for MavenExecutionContextView.getLocalRepository
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java
Labels: enhancement

#4486 Also show details for singular MavenDownloadingException
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
Labels: enhancement

#4483 Improve handling of inner classes
  rewrite-java-test/src/test/java/org/openrewrite/java/OrderImportsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
  rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
Labels: bug

#4493 RemoveRedundantDependencyVersions handles pluginManagement incorrectly
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveRedundantDependencyVersionsTest.java
Labels: bug

#4502 Add declarative Gradle upgrade recipes
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-5.yml
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-6.yml
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-7.yml
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-8.yml
Labels: recipe

#4504 Handle bom import in RemoveDuplicateDependencies
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveDuplicateDependencies.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveDuplicateDependenciesTest.java
Labels: bug, enhancement

#4509 Drop `OperatorWrap` as there's a copy maintained in rewrite-static-analysis
  rewrite-java-test/src/test/java/org/openrewrite/java/format/OperatorWrapTest.java
  rewrite-java/src/main/java/org/openrewrite/java/format/OperatorWrap.java
Labels: enhancement

#4512 Use `maven-metadata-local.xml` for `file://` paths
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
Labels: enhancement

#4516 Accommodate Java 23 in ReloadableJava21ParserVisitor
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
Labels: bug, parser-java

#4517 Only bump Maven plugin version property when needed
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java
Labels: bug

#4518 Parse .NET .vbproj and .fsproj files as XML
  rewrite-xml/src/main/java/org/openrewrite/xml/XmlParser.java
  rewrite-xml/src/test/java/org/openrewrite/xml/XmlParserTest.java
Labels: bug

#4506 Use `OPTIONS` request before falling back to `HEAD` request when trying to connect to repositories during normalization.
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Labels: enhancement

#4491 Adding gradle wrapper through distribution is now possible
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
Labels: bug, enhancement

#4535 Drop AllArgsConstructor from RawPom$Build
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
Labels: bug
