Repository openrewrite/rewrite, pull requests merged in 2024-01, with the labels that each got.

#3872 Check "var" keyword when varType is null or JCErroneous
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/VariableDeclarationsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/FinalizeLocalVariablesTest.java
Labels: bug, parser-java

#3878 Simplify `!(false)` and `!((false))`
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitor.java
Labels: enhancement

#3885 Missing type tag in AddDependencyVisitor
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDependencyVisitor.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
Labels: bug, enhancement

#3886 refactor: Minimal indentation for `SourceSpecs` text blocks
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateInstanceOfTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/ShortenFullyQualifiedTypeReferencesTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddDevelocityMavenExtensionTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddPluginTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AssertionsTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeProjectVersionTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/OrderPomElementsTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveExclusionTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveManagedDependencyTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemovePluginDependencyTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveRedundantDependencyVersionsTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/ChangeNamespaceValueTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/format/AutoFormatTest.java
Labels: enhancement

#3887 Supporting changing name of implicit `value` attributes in ChangeAnnotationAttributeName
  rewrite-java/src/main/java/org/openrewrite/java/ChangeAnnotationAttributeName.java
  rewrite-java/src/test/java/org/openrewrite/java/ChangeAnnotationAttributeNameTest.java
Labels: bug, enhancement

#3888 Add `RemoveAnnotationAttribute` recipe
  rewrite-java/src/main/java/org/openrewrite/java/RemoveAnnotationAttribute.java
  rewrite-java/src/test/java/org/openrewrite/java/RemoveAnnotationAttributeTest.java
Labels: recipe

#3868 Preserve space and comments after import in RemoveImport
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveImportTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveImport.java
Labels: bug

#3894 Do not simplify two identical method calls
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitor.java
Labels: bug

#3896 Do not unwrap parentheses around negated ternary
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/UnwrapParentheses.java
Labels: bug

#3906 Fix LOWER_CAMEL, UPPER_CAMEL to handle uppercase abbreviation better
  rewrite-core/src/main/java/org/openrewrite/internal/NameCaseConvention.java
  rewrite-core/src/test/java/org/openrewrite/internal/NameCaseConventionTest.java
Labels: enhancement

#3889 Validate that Change(Managed)DependencyGroupIdAndArtifactId updates GAV
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactIdTest.java
Labels: recipe

#3914 Fix `TypesInUse` regression
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/TypesInUse.java
Labels: bug

#3917 Find `@Option` annotations without `example` values
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/MissingOptionExampleTest.java
  rewrite-java/src/main/java/org/openrewrite/java/recipes/MissingOptionExample.java
Labels: recipe

#3920 Allow regular expressions on `ChangeTagAttribute`
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java
  rewrite-xml/src/main/java/org/openrewrite/xml/ChangeTagAttribute.java
  rewrite-xml/src/test/java/org/openrewrite/xml/ChangeTagAttributeTest.java
Labels: enhancement

#3930 Perform same newGroupId and newArtifactId validations for Gradle ChangeDependency recipe
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
Labels: enhancement

#3901 Add support for gradle dependency versions to be updated in gradle.properties
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Labels: enhancement

#3931 Plugin configuration can be null
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Plugin.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: bug

#3918 Change primitive handling in RemoveObjectsIsNull
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveObjectsIsNullTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveObjectsIsNull.java
Labels: bug

#3934 Tests for XPathMatcher #3919
  rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
Labels: test provided

#3936 `MavenParser` allows skipping dependency resolution
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: enhancement

#3940 Skip NoWhitespaceBefore and NoWhitespaceBefore for Groovy
  rewrite-java-test/build.gradle.kts
  rewrite-java-test/src/test/java/org/openrewrite/java/format/NoWhitespaceBeforeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/format/NoWhitespaceAfter.java
  rewrite-java/src/main/java/org/openrewrite/java/format/NoWhitespaceBefore.java
Labels: bug

#3939 Do not downgrade SourceCompatibility by default
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateJavaCompatibility.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateJavaCompatibilityTest.java
Labels: bug

#3941 Reintroduce recipe run cycles
  rewrite-core/openrewrite.json
  rewrite-core/src/main/java/org/openrewrite/DataTable.java
  rewrite-core/src/main/java/org/openrewrite/ExecutionContext.java
  rewrite-core/src/main/java/org/openrewrite/FindCollidingSourceFiles.java
  rewrite-core/src/main/java/org/openrewrite/Recipe.java
  rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
  rewrite-core/src/main/java/org/openrewrite/Repeat.java
  rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
  rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
  rewrite-core/src/main/java/org/openrewrite/internal/InMemoryLargeSourceSet.java
  rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeRunCycle.java
  rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeStack.java
  rewrite-core/src/main/java/org/openrewrite/scheduling/WorkingDirectoryExecutionContextView.java
  rewrite-core/src/main/java/org/openrewrite/text/AppendToTextFile.java
  rewrite-core/src/test/java/org/openrewrite/ExecutionContextTest.java
  rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java
  rewrite-core/src/test/java/org/openrewrite/RecipeSchedulerTest.java
  rewrite-core/src/test/java/org/openrewrite/TreeObserverTest.java
  rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java
  rewrite-core/src/test/java/org/openrewrite/table/RecipeRunStatsTest.java
  rewrite-core/src/test/java/org/openrewrite/text/AppendToTextFileTest.java
  rewrite-core/src/test/java/org/openrewrite/text/FindAndReplaceTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyVisitorTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/cleanup/SimplifyBooleanExpressionVisitorTest.java
  rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclAttributeTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/InvertConditionTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateAnnotationTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateImportTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateSubstitutionsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest2Test.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaVisitorTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/UpdateSourcePositionsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/recipes/FindRecipesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddManagedDependencyVisitor.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddManagedDependencyVisitorTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddProfileTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveDuplicateDependenciesTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenWrapperTest.java
  rewrite-test/src/main/java/org/openrewrite/test/AdHocRecipe.java
  rewrite-test/src/main/java/org/openrewrite/test/AdHocScanningRecipe.java
  rewrite-test/src/main/java/org/openrewrite/test/LargeSourceSetCheckingExpectedCycles.java
  rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
  rewrite-test/src/test/java/org/openrewrite/config/EnvironmentTest.java
  rewrite-test/src/test/java/org/openrewrite/test/RewriteTestTest.java
  rewrite-test/src/test/java/org/openrewrite/test/internal/RewriteTestTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/ChangeTagAttributeTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/RemoveContentTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/security/IsOwaspSuppressionsFileTest.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/CreateYamlFile.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Labels: bug

#3933 Adding support for plugin versions in gradle.properties file
  rewrite-gradle/src/main/java/org/openrewrite/gradle/IsBuildGradle.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/IsSettingsGradle.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/UpgradePluginVersionTest.java
Labels: enhancement

#3947 Upgrade plugin versions in gradle.properties
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/UpgradePluginVersionTest.java
Labels: bug

#3955 fix: prevent all referenced properties from updating to latest regardless of recipe
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Labels: bug

#3960 Make DependencyUseStringNotation compatible with G.GString
  rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseStringNotation.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/DependencyUseStringNotationTest.java
Labels: bug, enhancement
