Repository openrewrite/rewrite, pull requests merged in 2025-04, with the labels that each got.

#5226 Fix for Java parser when no space between modifier and annotation
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/AnnotationTest.java
Labels: bug, parser-java

#5245 Add a new `UnfoldProperties` recipe
  rewrite-yaml/src/main/java/org/openrewrite/yaml/UnfoldProperties.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/UnfoldPropertiesTest.java
Labels: recipe

#5256 Adopt JSpecify in `EmptyBlockStyle` & `OperatorWrapStyle` without breaking `CheckstyleConfigLoaderTest`
  rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/EmptyBlockStyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/OperatorWrapStyle.java
Labels: enhancement

#5243 Enhance UseMavenCompilerPluginReleaseConfiguration Recipe to update the plugin configuration in profile section
  rewrite-maven/src/main/java/org/openrewrite/maven/UseMavenCompilerPluginReleaseConfiguration.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UseMavenCompilerPluginReleaseConfigurationTest.java
Labels: enhancement

#5257 Update `ChangePluginGroupIdAndArtifactId` descriptions
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactId.java
Labels: bug

#5252 Add data table that records all download attempts of any Maven POM or metadata
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyVersionSelector.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePlugin.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/ChangePlugin.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/ChangePluginVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/MigrateGradleEnterpriseToDevelocity.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDependencyVisitor.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddManagedDependency.java
  rewrite-maven/src/main/java/org/openrewrite/maven/AddParentPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeTransitiveDependencyVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/main/java/org/openrewrite/maven/table/MavenDownloadEvents.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenDownloadEventsTest.java
Labels: enhancement

#5253 Determine parenthesis level for `ConstructorCallExpression` and `ConstantExpression` when using Groovy 2
  rewrite-groovy/src/groovy2Test/java/org/openrewrite/groovy/GroovyParserTest.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Labels: bug, parser-groovy

#5158 Gradle Kotlin DSL recipes
  rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyConstraintToRule.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/IsBuildGradle.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/IsSettingsGradle.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/search/FindJVMTestSuites.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/trait/GradleDependency.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveDependencyTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
Labels: enhancement

#5272 Use consistent license headers for files moved here
  rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodInvocationReturnType.java
  rewrite-java/src/main/java/org/openrewrite/java/ReplaceStringLiteralValue.java
  rewrite-java/src/test/java/org/openrewrite/java/ChangeMethodInvocationReturnTypeTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UseMavenCompilerPluginReleaseConfiguration.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersionTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UseMavenCompilerPluginReleaseConfigurationTest.java
Labels: documentation

#5235 Fix generated code for generics
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateContextFreeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: bug, parser-java

#5222 add preconditions getter to Declarative Recipe
  rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
Labels: enhancement

#5275 `JavaTemplate` parenthesizes expressions as required
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
Labels: enhancement

#5274 XML parser - Accepting input with just \r characters as newlines
  rewrite-xml/src/main/antlr/XMLLexer.g4
  rewrite-xml/src/main/antlr/XMLLexer.tokens
  rewrite-xml/src/main/java/org/openrewrite/xml/internal/grammar/XMLLexer.interp
  rewrite-xml/src/main/java/org/openrewrite/xml/internal/grammar/XMLLexer.java
  rewrite-xml/src/main/java/org/openrewrite/xml/internal/grammar/XMLLexer.tokens
  rewrite-xml/src/main/java/org/openrewrite/xml/internal/grammar/XMLParser.interp
  rewrite-xml/src/main/java/org/openrewrite/xml/internal/grammar/XMLParser.java
  rewrite-xml/src/main/java/org/openrewrite/xml/internal/grammar/XMLParser.tokens
  rewrite-xml/src/test/java/org/openrewrite/xml/XmlParserTest.java
Labels: parser-xml

#5278 Add support for Groovy `!in` operator
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/G.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java
Labels: enhancement, parser-groovy

#5280 Add generic types to JavaTemplate
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyTemplate.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/internal/template/GroovySubstitutions.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateGenericsTest.java
  rewrite-java/src/main/antlr/TemplateParameterLexer.g4
  rewrite-java/src/main/antlr/TemplateParameterParser.g4
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplateSemanticallyEqual.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterLexer.interp
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterLexer.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterLexer.tokens
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParser.interp
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParser.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParser.tokens
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserBaseListener.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserBaseVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserListener.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/TypeParameter.java
  rewrite-java/src/test/java/org/openrewrite/java/internal/template/TypeParameterTest.java
  rewrite-kotlin/src/main/java/org/openrewrite/kotlin/KotlinTemplate.java
  rewrite-kotlin/src/main/java/org/openrewrite/kotlin/cleanup/ReplaceCharToIntWithCode.java
  rewrite-kotlin/src/main/java/org/openrewrite/kotlin/internal/template/KotlinSubstitutions.java
Labels: enhancement

#5285 Exclude TCK module from recipe-bom
  rewrite-bom/build.gradle.kts
Labels: enhancement

#5286 Fix bug where `a` is not equal to `this.a` in a setter
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/search/SemanticallyEqualTest.java
  rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: bug

#5307 Unwrap parentheses around method invocation arguments
  rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesVisitor.java
Labels: enhancement

#5309 feat: support JDK24
  rewrite-java-21/build.gradle.kts
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeMapping.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeSignatureBuilder.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/internal/Javac.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/internal/JavacTreeMaker.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/internal/Permit.java
Labels: parser-java, java 25+

#5322 Remove warnings from Gradle build logFix
  rewrite-kotlin/build.gradle.kts
  rewrite-kotlin/src/main/java/org/openrewrite/kotlin/KotlinTypeGoat.kt
  rewrite-kotlin/src/main/kotlin/org/openrewrite/kotlin/KotlinIrTypeMapping.kt
  rewrite-kotlin/src/main/kotlin/org/openrewrite/kotlin/KotlinTypeMapping.kt
  rewrite-kotlin/src/main/kotlin/org/openrewrite/kotlin/internal/IrTreePrinterVisitor.kt
  rewrite-kotlin/src/test/resources/KotlinTypeGoat.kt
Labels: enhancement, parser-kotlin

#5326 refactor: Extract documentation examples from tests
  rewrite-groovy/src/main/resources/META-INF/rewrite/examples.yml
  rewrite-hcl/src/main/resources/META-INF/rewrite/examples.yml
  rewrite-java-test/src/main/resources/META-INF/rewrite/examples.yml
  rewrite-java/src/main/resources/META-INF/rewrite/examples.yml
  rewrite-json/src/main/resources/META-INF/rewrite/examples.yml
  rewrite-kotlin/src/main/resources/META-INF/rewrite/examples.yml
  rewrite-maven/src/main/resources/META-INF/rewrite/examples.yml
  rewrite-properties/src/main/resources/META-INF/rewrite/examples.yml
  rewrite-xml/src/main/resources/META-INF/rewrite/examples.yml
  rewrite-yaml/src/main/resources/META-INF/rewrite/examples.yml
Labels: documentation

#5330 Added option.release as a field that can set the java version.
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateJavaCompatibility.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateJavaCompatibilityTest.java
Labels: bug

#5317 Add support for Groovy spread operator.
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/G.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/GLeftPadded.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/GSpace.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyVisitorTest.java
Labels: enhancement, parser-groovy

#5336 Rename deprecated JaCoCo properties as part of Gradle 8 migration
  rewrite-gradle/src/main/java/org/openrewrite/gradle/gradle8/JacocoReportDeprecations.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/gradle8/package-info.java
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-8.yml
  rewrite-gradle/src/test/java/org/openrewrite/gradle/gradle8/JacocoReportDeprecationsTest.java
Labels: recipe

#5282 Introduce recipes to rename Type and Package in Java String literals
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangePackageInStringLiteral.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeTypeInStringLiteral.java
  rewrite-java/src/test/java/org/openrewrite/java/ChangePackageInStringLiteralTest.java
  rewrite-java/src/test/java/org/openrewrite/java/ChangeTypeInStringLiteralTest.java
Labels: bug

#5338 Add `DependencyPluginGoalResolveSources` recipe for Maven
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/main/java/org/openrewrite/maven/plugin/DependencyPluginGoalResolveSources.java
  rewrite-maven/src/main/resources/META-INF/rewrite/maven.yml
  rewrite-maven/src/test/java/org/openrewrite/maven/plugin/DependencyPluginGoalResolveSourcesTest.java
Labels: recipe

#5340 Support Scanning Recipes as preconditions in DeclarativeRecipe.
  rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
  rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
  rewrite-core/src/main/java/org/openrewrite/search/RepositoryContainsFile.java
  rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/search/ModuleHasPlugin.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/search/ModuleHasPluginTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/search/ModuleHasPlugin.java
Labels: enhancement

#5351 Do not bring named parameters out of their containing MapExpression when in an Map with a prefixed space.
  rewrite-gradle/src/test/java/org/openrewrite/gradle/GradleParserTest.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Labels: bug, parser-groovy

#5354 Add test for open issue after some other fixes
  rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java
Labels: bug, parser-groovy

#5321 Add support for "new array" in Groovy parser.
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyVisitorTest.java
Labels: parser-groovy

#5356 Do not bump transitive dependencies if there is a direct dependency also
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
Labels: bug
