Repository openrewrite/rewrite, pull requests merged in 2025-05, with the labels that each got.

#5348 Support two modes for handling `GenericTypeVariables` in `TypeUtils.isAssignableTo(..)` and `TypeUtils.isOfType(..)`
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsAssertions.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplateSemanticallyEqual.java
  rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/Types.java
Labels: bug, enhancement

#5367 Add Maven plugin dependency with implied groupId
  rewrite-maven/src/main/java/org/openrewrite/maven/AddPluginDependency.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddPluginDependencyTest.java
Labels: enhancement, recipe

#5366 Replace `J.MethodInvocation`s with constant
  rewrite-java/src/main/java/org/openrewrite/java/ReplaceMethodInvocationWithConstant.java
  rewrite-java/src/test/java/org/openrewrite/java/ReplaceMethodInvocationWithConstantTest.java
Labels: enhancement

#5369 Fix regression in RenameVariable
  rewrite-java-test/src/test/java/org/openrewrite/java/RenameVariableTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
Labels: bug

#5372 Restore TypeUtils.isOfType behaviour
  rewrite-java-test/src/test/java/org/openrewrite/java/RenameVariableTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: bug

#5375 Fix managed dependency equality around nullable classifier & type
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveDuplicateDependenciesTest.java
  rewrite-maven/src/test/resources/junit-platform.properties
Labels: bug, recipe, parser-maven

#5381 Associate CustomImportOrderStyle with Checkstyle styles
  rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java
  rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java
  rewrite-java/src/main/java/org/openrewrite/java/style/CustomImportOrderStyle.java
  rewrite-java/src/test/java/org/openrewrite/java/style/CheckstyleConfigLoaderTest.java
Labels: enhancement

#5396 Added Java parser tests for constructors, with some statements before super/this
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ConstructorTest.java
Labels: discovery, java 25+

#5398 PropertyPlaceholderHelper Not Handling Lack of Separation Between Placeholders
  rewrite-core/src/main/java/org/openrewrite/internal/PropertyPlaceholderHelper.java
  rewrite-core/src/test/java/org/openrewrite/internal/PropertyPlaceholderHelperTest.java
Labels: bug, test provided

#5395 Throw for unhandled `ParseError` in `RewriteTest` to avoid `ClassCastException`
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Labels: enhancement

#5399 Paving the core concepts for LockFile creation recipe
  rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java
  rewrite-core/src/main/java/org/openrewrite/text/PlainText.java
  rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/Assertions.java
Labels: bug, enhancement

#5401 Cleanup RemoveRedundantDependencyVersions recipe
  rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveRedundantDependencyVersions.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveRedundantDependencyVersionsTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
Labels: recipe

#5404 Add fallback when attempting to load `lombok.launch.ShadowClassLoader`
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/LombokSupport.java
Labels: bug

#5406 `RenameVariable` fixes for member references
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/RenameVariableTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
  rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
Labels: enhancement

#5412 Mark methods overridden from classes as `isOverride()`
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Labels: bug

#5382 Not visiting Javadoc contents in JavaTemplate.apply
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateJavadocTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java
Labels: bug, enhancement

#5421 Added checks to leave builtscript alone in DependencyConstraintToRule
  rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyConstraintToRule.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/DependencyConstraintToRuleTest.java
Labels: bug, recipe

#5417 Resolve managed dependency with 'RELEASE' or 'LATEST' versions.
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: bug

#5429 Add support for partially unfolding single line yaml properties with exclusions in UnfoldProperties
  rewrite-yaml/src/main/java/org/openrewrite/yaml/UnfoldProperties.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/UnfoldPropertiesTest.java
Labels: bug, recipe, test provided

#5436 Move gradle Traits Utility
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyArtifactId.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyClassifier.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyConfiguration.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyExtension.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyGroupId.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseMapNotation.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseStringNotation.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveRedundantDependencyVersions.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/trait/Traits.java
Labels: recipe

#5438 Added support for index visitation and all matching elements when filtering
  rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/AppendToSequenceTest.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/JsonPathMatcherTest.java
Labels: bug, enhancement

#5425 Update transitive dependencies and platforms in a gradle lockfile
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateDependencyLock.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/marker/GradleDependencyConfiguration.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/search/FindGradleProject.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/LockDependencyVersionsTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawGradleModule.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/utilities/MavenArtifactDownloaderTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/utilities/PrintMavenAsDotTest.java
Labels: enhancement, recipe

#5405 "No version provided" for managed Maven dependencies with type
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: bug, parser-maven

#5433 Do not `AddDependency` for transitive dependency managed by a bom, even if `onlyIfUsing == null`
  rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
Labels: bug

#5442 Only allow gradle dependency locking for already locked configurations/artifacts
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateDependencyLock.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/LockDependencyVersionsTest.java
Labels: bug

#5447 Consistently use `testRuntimeOnly(project(":rewrite-java-21"))`
  rewrite-benchmarks/build.gradle.kts
  rewrite-gradle/build.gradle.kts
  rewrite-groovy/build.gradle.kts
  rewrite-java-tck/build.gradle.kts
  rewrite-java-test/build.gradle.kts
  rewrite-java/build.gradle.kts
  rewrite-javascript/build.gradle.kts
  rewrite-kotlin/build.gradle.kts
  rewrite-kotlin/src/test/java/org/openrewrite/kotlin/KotlinTypeMappingTest.java
  rewrite-maven/build.gradle.kts
Labels: enhancement

#5453 Fixed the scanner being executed in a loop that then causes all scans to be updated in a single run.
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
Labels: bug

#5420 Support infer mode
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsAssertions.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateGenericsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplateSemanticallyEqual.java
  rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Labels: enhancement

#5456 Continue type attribution in a case of exception
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21Parser.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java
Labels: enhancement, parser-java

#5462 Fix `ConcurrentModificationException` in `TypeTable`
  rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java
Labels: bug

#5497 Fixing multiline html comment
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
Labels: bug, parser-java

#5500 Add an `applyTo` option to the UnfoldProperties recipe
  rewrite-yaml/src/main/java/org/openrewrite/yaml/UnfoldProperties.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/UnfoldPropertiesTest.java
Labels: recipe

#5503 Generalize changing of properties in Maven recipes
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactIdTest.java
Labels: recipe

#5408 RecipeRunStats several times counts the same recipe runs with different params
  rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeRunCycle.java
  rewrite-core/src/main/java/org/openrewrite/table/RecipeRunStats.java
  rewrite-core/src/test/java/org/openrewrite/table/RecipeRunStatsTest.java
Labels: bug

#5384 Add expression type in JavaTemplate
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateGenericsTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
  rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
Labels: enhancement

#5519 Annotate nullable methods that return from ternary
  rewrite-core/src/main/java/org/openrewrite/rpc/RpcReceiveQueue.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveRepository.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/JsonPathMatcher.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/ClassIdResolver.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
  rewrite-json/src/main/java/org/openrewrite/json/JsonPathMatcher.java
  rewrite-kotlin/src/main/java/org/openrewrite/kotlin/cleanup/RemoveTrailingSemicolon.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenXmlMapper.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java
Labels: enhancement

#5373 Move file to another directory
  rewrite-core/src/main/java/org/openrewrite/MoveFile.java
  rewrite-core/src/test/java/org/openrewrite/MoveFileTest.java
Labels: recipe

#5525 Skip importing inner type if outer class is already imported
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
Labels: bug

#5454 Rename variables if the name matches class name
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Labels: enhancement

#5533 Handle non-literal arguments in AddOrUpdateAnnotationAttribute
  rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
Labels: bug
