Repository openrewrite/rewrite, pull requests merged in 2025-06, with the labels that each got.

#5549 Fixed that the YAML DeleteKey does not remove unused parent keys in all situations
  rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteKey.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/DeleteKeyTest.java
Labels: enhancement

#5551 Retrieving all licenses currently used in recipe jars
  rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
  rewrite-core/src/main/java/org/openrewrite/config/Environment.java
  rewrite-core/src/main/java/org/openrewrite/config/License.java
  rewrite-core/src/main/java/org/openrewrite/config/ResourceLoader.java
  rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
  rewrite-core/src/test/java/org/openrewrite/config/EnvironmentTest.java
Labels: enhancement

#5531 Handling unterminated inline tags
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
Labels: bug, parser-javadoc

#5567 Fixed some detection logic for DependencyInsight in gradle.
  rewrite-gradle/src/main/java/org/openrewrite/gradle/search/DependencyInsight.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/search/DependencyInsightTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/search/DependencyInsight.java
  rewrite-maven/src/main/java/org/openrewrite/maven/table/DependenciesInUse.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedDependency.java
Labels: bug

#5353 Fix: Yaml parser cannot parse Yaml files containing anchors with sequences on root level
  rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Labels: bug, parser-yaml

#5544 Implement annotation wrapping style detection, IntelliJ default and applying
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest5Test.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest6Test.java
  rewrite-java-test/src/test/java/org/openrewrite/java/format/WrappingAndBracesTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java
  rewrite-java/src/main/java/org/openrewrite/java/format/WrappingAndBracesVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
  rewrite-java/src/main/java/org/openrewrite/java/style/IntelliJ.java
  rewrite-java/src/main/java/org/openrewrite/java/style/WrappingAndBracesStyle.java
Labels: enhancement

#5590 Annotation wrapping: Leave comments in tact
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest5Test.java
  rewrite-java-test/src/test/java/org/openrewrite/java/format/WrappingAndBracesTest.java
  rewrite-java/src/main/java/org/openrewrite/java/format/WrappingAndBracesVisitor.java
Labels: bug

#5607 Datatable should not have the direct column
  rewrite-gradle/src/main/java/org/openrewrite/gradle/search/DependencyInsight.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/search/DependencyInsightTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/search/DependencyInsight.java
  rewrite-maven/src/main/java/org/openrewrite/maven/table/DependenciesInUse.java
Labels: bug

#5606 Enhance MavenSettings to handle password decryption
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenSecuritySettings.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenSettings.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenSettingsTest.java
Labels: bug

#5618 Fix: handle nested type annotations on array
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/AnnotationTest.java
Labels: bug, parser-java

#5629 Add support for Elvis assignment operator in Groovy parser
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/G.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ElvisAssignmentTest.java
Labels: parser-groovy

#5625 Fix parsing of generics in anonymous class in Groovy
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java
Labels: bug, parser-groovy

#5632 Added check for missing attributeName, but attributeValue requirement in `AddOrUpdateAnnotationAttribute`
  rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
Labels: bug, recipe

#5656 Cleanup: ChangeParentPom recipe
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
Labels: recipe

#5659 Fixed UpdateGradleWrapper description to represent behaviour
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
Labels: documentation

#5610 Polish the Gradle build's configuration phase
  rewrite-gradle/build.gradle.kts
  rewrite-java-11/build.gradle.kts
  rewrite-java-17/build.gradle.kts
  rewrite-java-21/build.gradle.kts
  rewrite-java-tck/build.gradle.kts
  rewrite-java-test/build.gradle.kts
  rewrite-java/build.gradle.kts
  rewrite-javascript/build.gradle.kts
  rewrite-javascript/rewrite/package.json
  rewrite-javascript/rewrite/tsconfig.build.json
  rewrite-maven/build.gradle.kts
  rewrite-xml/build.gradle.kts
Labels: performance

#5681 Pin JUnit to 5.+
  rewrite-test/build.gradle.kts
Labels: bug, dependencies

#5682 Adjusting the `isValid` check for `XRange` so that it doesn't allow for going from release to pre-release versions when upgrading.
  rewrite-core/src/main/java/org/openrewrite/semver/XRange.java
  rewrite-core/src/test/java/org/openrewrite/semver/XRangeTest.java
Labels: bug, test provided
