Repository openrewrite/rewrite, pull requests merged in 2025-02, with the labels that each got.

#4981 Preserve spacing when merging flow style YAML
  rewrite-yaml/src/main/java/org/openrewrite/yaml/format/MinimumViableSpacingVisitor.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Labels: bug

#4982 Support duplicate static star imports for Groovy
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ImportTest.java
Labels: bug, parser-groovy

#4986 Replace `NavigableMap<LineColumn, List<ASTNode>>` to `NavigableMap<LineColumn, ASTNode>`, because it's impossible to have multiple elements at the very same line and column
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Labels: parser-groovy

#4987 Use `sourceStartsWith` to simplify visitClass
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Labels: parser-groovy

#4989 Enable Lombok by default on Java 11+
  IDE.properties.tmp
  rewrite-gradle/src/test/java/org/openrewrite/maven/tree/OpenRewriteModelSerializableTest.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21Parser.java
  rewrite-java-lombok/build.gradle.kts
  rewrite-java-lombok/libs/lombok-1.18.37.jar
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/LombokTest.java
Labels: enhancement, parser-java

#4270 Activated profiles should not always deactivate POM profiles that are active by default
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: bug

#4990 Support duplicate star imports with comments
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ImportTest.java
Labels: bug

#4991 Disable parentheses level discovery for method calls for groovy 2
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Labels: bug

#4994 Skip GitProvenance for bare repositories
  rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java
Labels: bug

#5001 Groovy parser does not support annotations on variable declarations
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/internal/Delimiter.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AnnotationTest.java
Labels: enhancement, parser-groovy

#5003 Fixes potential `StringIndexOutOfBoundsException` in Java parser
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/LombokTest.java
Labels: bug

#4999 Validate written classes if enabled, and fix reported issues
  rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java
  rewrite-java/src/test/java/org/openrewrite/java/internal/parser/TypeTableTest.java
Labels: bug

#5010 Fix NullPointerException in Java parser for Enums with missing type information
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
Labels: bug

#5011 Disable Lombok again
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21Parser.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/LombokTest.java
Labels: bug, parser-java

#5018 Fixing JavaTemplateParser wrt method arguments replacement - removing extra semicolon
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateSubstitutionsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
Labels: bug

#5023 Add `ResolutionEventListener` event whenever a repository normalization attempt is skipped
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolutionEventListener.java
Labels: enhancement

#5014 Create TypeTable entries for empty marker annotations
  rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java
  rewrite-java/src/test/java/org/openrewrite/java/internal/parser/TypeTableTest.java
Labels: bug

#4934 Amending YAML parser to add support for tags
  rewrite-yaml/src/main/java/org/openrewrite/yaml/AppendToSequenceVisitor.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangeValue.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/CountLinesVisitor.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlIsoVisitor.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlVisitor.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/internal/YamlPrinter.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/tree/Yaml.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/CountLinesVisitorTest.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Labels: bug, parser-yaml

#5033 Centralize Lombok initialization logic
  rewrite-core/src/main/java/org/openrewrite/internal/ReflectionUtils.java
  rewrite-java-11/build.gradle.kts
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
  rewrite-java-17/build.gradle.kts
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
  rewrite-java-21/build.gradle.kts
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21Parser.java
  rewrite-java-8/build.gradle.kts
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java
  rewrite-java-lombok/build.gradle.kts
  rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/LombokSupport.java
Labels: bug

#5043 Read all TypeTable `classpath.tsv.zip` files
  rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java
  rewrite-java/src/test/java/org/openrewrite/java/internal/parser/TypeTableTest.java
Labels: bug

#5045 Support modifiers for Groovy method declaration parameters
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodDeclarationTest.java
Labels: parser-groovy

#5041 Groovy - fix support for import statements following multiline comments
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserVisitorTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ImportTest.java
Labels: bug, parser-groovy

#4996 fix: handle comment at the end of a method declaration
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/CommentTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
Labels: bug, parser-java

#5048 Groovy Parser - Improve retrieval of modifiers
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/main/java/org/openrewrite/groovy/marker/RedundantDef.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodDeclarationTest.java
Labels: parser-groovy

#5000 Add dependencies in JVMTestSuite dependency block
  rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/search/FindJVMTestSuites.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/table/JVMTestSuitesDefined.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/search/FindJVMTestSuitesTest.java
Labels: enhancement

#5036 Improve MergeYaml recipe
  rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/CopyValue.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYamlVisitor.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Labels: bug, recipe

#5064 Record a SourcesFileResults.Row for generated sources
  rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeRunCycle.java
Labels: enhancement

#5068 Restore Yaml.* constructors without Tag for gradual adoption
  rewrite-yaml/src/main/java/org/openrewrite/yaml/tree/Yaml.java
Labels: bug, enhancement

#5076 Java parsing fix for empty comment as last line
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/CommentTest.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
Labels: bug, parser-java

#5063 Parser failures with unnecessary semicolons
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ClassDeclarationTest.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/NewClassTest.java
Labels: bug, parser-java

#5077 Fixing handling of trailing empty single-line comment
  rewrite-hcl/src/main/java/org/openrewrite/hcl/tree/Space.java
  rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclCommentTest.java
  rewrite-json/src/main/java/org/openrewrite/json/tree/Space.java
  rewrite-json/src/test/java/org/openrewrite/json/JsonParserTest.java
  rewrite-toml/src/main/java/org/openrewrite/toml/tree/Space.java
  rewrite-toml/src/test/java/org/openrewrite/toml/TomlParserTest.java
Labels: bug, parser-hcl, parser-json, parser-toml

#5089 Put the `getCommentTree` reflection code back in the Java 17 parser
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
Labels: enhancement

#5070 Parse properties from `maven.config` file
  rewrite-maven/src/main/java/org/openrewrite/maven/Assertions.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: bug

#5091 More compact `AdaptiveRadixTree`
  rewrite-core/src/main/java/org/openrewrite/internal/AdaptiveRadixTree.java
Labels: performance

#5092 Remove Snappy dependency
  rewrite-benchmarks/build.gradle.kts
  rewrite-benchmarks/src/jmh/java/org/openrewrite/benchmarks/java/JavaCompilationUnitState.java
  rewrite-benchmarks/src/jmh/java/org/openrewrite/benchmarks/java/JavaParserBenchmark.java
  rewrite-benchmarks/src/jmh/java/org/openrewrite/benchmarks/java/JavaTypeCacheBenchmark.java
  rewrite-core/src/main/java/org/openrewrite/internal/AdaptiveRadixTree.java
  rewrite-java/build.gradle.kts
  rewrite-java/src/main/java/org/openrewrite/java/internal/AdaptiveRadixJavaTypeCache.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/JavaTypeCache.java
Labels: performance

#5090 Fix parsing of multi-line comments "containing" single-line comments
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/CompilationUnitTest.java
  rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/HclParserVisitor.java
  rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclCommentTest.java
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/CommentTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
  rewrite-json/src/test/java/org/openrewrite/json/JsonParserTest.java
  rewrite-protobuf/src/main/java/org/openrewrite/protobuf/internal/ProtoParserVisitor.java
  rewrite-protobuf/src/test/java/org/openrewrite/protobuf/tree/EmptyTest.java
Labels: bug

#5080 `ChangeType`: Use unqualified name if possible
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Labels: bug

#5098 Prove once more maven config properties are resolved
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
Labels: bug

#5097 MergeYaml recipe: Handle ParseError LSTs
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java
  rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYamlVisitor.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Labels: bug, recipe
