Repository openrewrite/rewrite, pull requests merged in 2025-03, with the labels that each got.

#5121 find-dependency-with-versions
  rewrite-gradle/src/main/java/org/openrewrite/gradle/search/FindDependency.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/search/FindDependencyTest.java
Labels: bug, recipe

#5132 Groovy Parser supports unassigned closure with GString as return value
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RealWorldGroovyTest.java
Labels: parser-groovy

#5137 Fix rewrite-kotlin tests
  rewrite-kotlin/build.gradle.kts
  rewrite-kotlin/src/main/java/org/openrewrite/kotlin/KotlinParser.java
Labels: bug

#5142 Fix groovy parser parsing package definition
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
  rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java
Labels: bug

#5122 Gradle Kotlin DSL
  rewrite-gradle/build.gradle.kts
  rewrite-gradle/src/main/java/org/openrewrite/gradle/Assertions.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/GradleParser.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/GradleParserTest.java
  rewrite-kotlin/src/main/java/org/openrewrite/kotlin/KotlinParser.java
Labels: enhancement

#5147 Handling enums with no values as J.EnumValueSet
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/EnumTest.java
Labels: bug, parser-java

#5164 Find method type references in JavaDoc in interfaces and superclasses
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
Labels: parser-java

#5167 Support this-constructor-links in JavaDoc
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Labels: parser-java

#5168 Fix handling of maven compiler plugin configuration for java version upgrade
  rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersion.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersionTest.java
Labels: bug

#5173 Assign response from `withTypeParameters` in `SpacesVisitor`
  rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
  rewrite-kotlin/src/main/java/org/openrewrite/kotlin/format/SpacesVisitor.java
Labels: bug

#5170 `JavaTemplate`: Add support for match arrays
  rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java
  rewrite-java/src/main/antlr/TemplateParameterLexer.g4
  rewrite-java/src/main/antlr/TemplateParameterParser.g4
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterLexer.interp
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterLexer.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterLexer.tokens
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParser.interp
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParser.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParser.tokens
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserBaseListener.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserBaseVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserListener.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/grammar/TemplateParameterParserVisitor.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/template/TypeParameter.java
  rewrite-java/src/test/java/org/openrewrite/java/internal/template/TypeParameterTest.java
Labels: enhancement

#5140 Fixes parsing of switch expression with combined null and default
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/SwitchPatternMatchingTest.java
Labels: bug, parser-java

#5183 Fix java version update
  rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersion.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersionTest.java
Labels: bug

#5185 When no version is present, skip resolving
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: bug

#5219 AddDependency recipe: Support only non-dependencies in Gradle's dependency block
  rewrite-gradle/src/main/java/org/openrewrite/gradle/internal/InsertDependencyComparator.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/internal/InsertDependencyComparator.java
Labels: bug

#5223 Re resolve repositories after resolving parent properties
  rewrite-core/src/main/java/org/openrewrite/internal/PropertyPlaceholderHelper.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Labels: bug, parser-maven

#5228 Precondition recipes must not produce data table rows
  rewrite-core/src/main/java/org/openrewrite/DataTable.java
  rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java
  rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeRunCycle.java
  rewrite-core/src/test/java/org/openrewrite/DataTableTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
  rewrite-test/src/main/java/org/openrewrite/test/AdHocRecipe.java
  rewrite-test/src/main/java/org/openrewrite/test/AdHocScanningRecipe.java
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Labels: bug

#5229 Support properties for RemoveExclusion recipe
  rewrite-maven/src/main/java/org/openrewrite/maven/RemoveExclusion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/search/FindDependency.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveExclusionTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/search/FindDependencyTest.java
Labels: bug

#5205 Empty objects in JSON to collapse in autoformatting
  rewrite-json/src/main/java/org/openrewrite/json/format/TabsAndIndentsVisitor.java
  rewrite-json/src/main/java/org/openrewrite/json/format/WrappingAndBracesVisitor.java
  rewrite-json/src/test/java/org/openrewrite/json/format/AutoFormatTest.java
Labels: parser-json

#5234 More efficient recipe loading
  rewrite-core/src/main/java/org/openrewrite/config/Environment.java
  rewrite-core/src/main/java/org/openrewrite/config/ResourceLoader.java
  rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
  rewrite-core/src/main/java/org/openrewrite/internal/RecipeIntrospectionUtils.java
  rewrite-core/src/main/java/org/openrewrite/internal/RecipeLoader.java
  rewrite-core/src/test/java/org/openrewrite/config/YamlResourceLoaderTest.java
Labels: performance
