Repository openrewrite/rewrite, pull requests merged in 2025-08, with the labels that each got.

#5857 Support Javadoc generic wildcards
  rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
  rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
  rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
  rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
  rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
  rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java
Labels: bug, javadoc, parser

#5848 fix: prevent variable renaming in class literal references
  rewrite-java-test/src/test/java/org/openrewrite/java/RenameVariableTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
Labels: bug, recipe

#5595 Always instantiate Kotlin recipes via Jackson
  rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
  rewrite-core/src/main/java/org/openrewrite/internal/ObjectMappers.java
  rewrite-core/src/main/java/org/openrewrite/internal/RecipeIntrospectionUtils.java
  rewrite-core/src/main/java/org/openrewrite/internal/RecipeLoader.java
  rewrite-kotlin/build.gradle.kts
  rewrite-kotlin/src/test/java/org/openrewrite/kotlin/KotlinFromDeclarativeRecipeTest.kt
Labels: bug

#5859 Fix the error message when a recipe test generates source files the test does not expect
  rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Labels: bug

#5821 Avoid overwriting parent pom from marker when going in child.
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenResolutionResult.java
  rewrite-maven/src/test/java/org/openrewrite/maven/RemoveLog4JBomTest.java
Labels: bug

#5866 Remove lambda parameter imports when inferred
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
  rewrite-java/src/main/java/org/openrewrite/java/internal/TypesInUse.java
Labels: enhancement

#5872 Ensure Maven parser uses last-wins strategy for duplicate dependencies
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/cleanup/PrefixlessExpressionsTest.java
Labels: bug

#5887 Extract common RewriteTest defaults for RecipeSpec
  rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveRepositoryTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/tree/TaskTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/ChangeMethodTargetToVariableTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/format/NormalizeFormatTest.java
  rewrite-java-test/src/test/java/org/openrewrite/java/search/UsesFieldTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AddAnnotationProcessorTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/AssertionsTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpdateScmFromGitOriginTest.java
  rewrite-maven/src/test/java/org/openrewrite/maven/search/FindScmTest.java
  rewrite-xml/src/test/java/org/openrewrite/xml/RemoveEmptyXmlTagsTest.java
  rewrite-yaml/src/test/java/org/openrewrite/yaml/ChangePropertyKeyTest.java
Labels: enhancement

#5815 `ChangeDependencyGroupIdAndArtifactId` does not update properties in parent pom
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
  rewrite-maven/src/main/java/org/openrewrite/maven/utilities/RetainVersions.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
Labels: bug, dependencies, maven

#5865 UpgradeTransitiveDependencyVersion should only compare name when comparing the config with the GradleDependencyConfiguration
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeTransitiveDependencyVersion.java
Labels: bug, recipe

#5893 Stable label order for `PrintMavenAsDot`
  rewrite-maven/src/main/java/org/openrewrite/maven/utilities/PrintMavenAsDot.java
  rewrite-maven/src/test/java/org/openrewrite/maven/utilities/PrintMavenAsDotTest.java
Labels: enhancement

#5884 Adding recipe for adding comments to import statements
  rewrite-java/src/main/java/org/openrewrite/java/AddCommentToImport.java
  rewrite-java/src/test/java/org/openrewrite/java/AddCommentToImportTest.java
Labels: enhancement, recipe, test provided

#5890 Make the parser settable on KotlinTemplate
  rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyTemplate.java
  rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
  rewrite-kotlin/src/main/java/org/openrewrite/kotlin/KotlinTemplate.java
  rewrite-kotlin/src/test/java/org/openrewrite/kotlin/KotlinTemplateTest.java
Labels: enhancement, kotlin

#5900 Call `UnnecessaryParenthesesVisitor` on parent after `RemoveObjectsIsNull`
  rewrite-java-test/src/test/java/org/openrewrite/java/RemoveObjectsIsNullTest.java
  rewrite-java/src/main/java/org/openrewrite/java/RemoveObjectsIsNull.java
  rewrite-maven/src/main/java/org/openrewrite/maven/tree/Dependency.java
Labels: bug

#5862 Imports from companion objects should have owningClass information
  rewrite-kotlin/src/main/kotlin/org/openrewrite/kotlin/KotlinTypeMapping.kt
  rewrite-kotlin/src/test/java/org/openrewrite/kotlin/tree/ImportTest.java
Labels: kotlin, parser

#5931 Fix `ClasspathScanningLoader` when inheritance hierarchy spans jars
  rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
  rewrite-core/src/test/java/org/openrewrite/config/ClasspathScanningLoaderTest.java
Labels: bug

#5945 Extending `AddCommentToMethodInvocations` to handle constructors as well
  rewrite-java/src/main/java/org/openrewrite/java/AddCommentToMethodInvocations.java
  rewrite-java/src/test/java/org/openrewrite/java/AddCommentToMethodInvocationsTest.java
Labels: enhancement, recipe, test provided

#5949 Set group and description for rewrite-gradle-tooling-model
  rewrite-gradle-tooling-model/model/build.gradle.kts
Labels: bug

#5934 Improve declaring type information for Kotlin top-level functions
  rewrite-kotlin/src/main/kotlin/org/openrewrite/kotlin/KotlinTypeMapping.kt
  rewrite-kotlin/src/main/kotlin/org/openrewrite/kotlin/KotlinTypeSignatureBuilder.kt
  rewrite-kotlin/src/test/java/org/openrewrite/kotlin/KotlinTypeMappingTest.java
Labels: kotlin, parser

#5953 Add `@InlineMe` and `InlineMethodCalls` recipe to replace annotated methods
  rewrite-java/src/main/java/org/openrewrite/java/InlineMe.java
  rewrite-java/src/main/java/org/openrewrite/java/InlineMethodCalls.java
  rewrite-java/src/test/java/org/openrewrite/java/InlineMethodCallsTest.java
Labels: recipe

#5899 Fix property resolution for dependencies with remote parent POMs
  rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
  rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
Labels: bug

#5964 Add support for resolving versions via Artifactory
  rewrite-core/src/main/java/org/openrewrite/remote/RemoteArchive.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/internal/GradleWrapperScriptDownloader.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/util/DistributionInfos.java
  rewrite-gradle/src/main/java/org/openrewrite/gradle/util/GradleWrapper.java
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-wrapper/unix/59e5bb1c.txt
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-wrapper/unix/8b67a07b.txt
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-wrapper/unix/908dbb2.txt
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-wrapper/unix/ae5b118f.txt
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-wrapper/unix/c310edb0.txt
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-wrapper/unix/d8a69f89.txt
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-wrapper/unix/dbe9ce75.txt
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-wrapper/versions.csv
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-wrapper/windows/b82de68.txt
  rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-wrapper/windows/c518efba.txt
  rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
  rewrite-gradle/src/test/java/org/openrewrite/gradle/internal/DistributionInfosTest.java
  rewrite-gradle/src/test/resources/gradle-8.8-all.zip
Labels: enhancement

#5969 InlineMethodCalls should handle delegating constructors
  rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependency.java
  rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodTargetToStatic.java
  rewrite-java/src/main/java/org/openrewrite/java/InlineMethodCalls.java
  rewrite-java/src/test/java/org/openrewrite/java/InlineMethodCallsTest.java
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
Labels: bug, recipe

#5880 ChangeDependencyGroupIdAndArtifactId should not limit updating managed dependencies
  rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
  rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
Labels: bug, recipe

#5962 "value" attr when adding another attribute
  rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java
  rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
Labels: bug, recipe

#5977 Compare `JavaType.Method.name` before `declaringType` in `equals(Object)`
  rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
  rewrite.yml
Labels: performance

#5973 Stop loading attribution
  rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
  rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
  rewrite-core/src/main/java/org/openrewrite/config/Environment.java
  rewrite-core/src/main/java/org/openrewrite/config/RecipeDescriptor.java
  rewrite-core/src/main/java/org/openrewrite/config/ResourceLoader.java
  rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
  rewrite-core/src/test/java/org/openrewrite/RecipeSchedulerTest.java
  rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java
  rewrite-core/src/test/java/org/openrewrite/config/YamlResourceLoaderTest.java
  rewrite-test/src/test/java/org/openrewrite/config/EnvironmentTest.java
Labels: enhancement, performance
